'use strict';(function(){function f(b,d){function g(b){if(b)return t.source?(b=new m.Promise,b.fulfill(),b):m.IO.loadAsync(t.id).then(function(b){t.source=b});t.source||(t.source=m.IO.loadSync(t.id))}function n(){t.ast=d.parse(t.source)}function l(b,c){t.ast.body.filter(function(b,c){return"ImportStatement"==b.type?(p.push(c),!0):!1}).forEach(function(b){b=b.uri.content;if(!(null===t.id||"/"==b[0])){var c=t.id.split("/").slice(0,-1).join("/");c?("/"==c[c.length-1]&&(c=c.slice(0,c.length-1)),b=c+"/"+
b):b="./"+b}b=new f(b,d);t.resources.push(b)});var g=[];t.resources.forEach(function(d){g.push(d.build(b,c))});if(c)return m.Promise.all(g)}function C(){for(var b=t.resources.length-1;0<=b;b--)Array.prototype.splice.apply(t.ast.body,[p[b]||0,1].concat(t.resources[b].ast.body));t.isReady=!0}var t=this;this.id=b;this.resources=[];this.source=null;this.isReady=!1;this.ast={type:"LOL",body:[]};this.build=function(b,d){if(7<=b)throw new c("Too many nested imports.");if(d)return g(d).then(n).then(l.bind(this,
b+1,d)).then(C);g(d);n();l(b+1,d);C()};var p=[]}function d(b,c,d){function g(b){var c=[];l.resources.forEach(function(d){c.push(d.build(0,b))});if(b)return m.Promise.all(c)}function f(){l.ast.body=l.resources.reduce(function(b,c){return b.concat(c.ast.body)},l.ast.body)}function n(){l.entries=d.compile(l.ast);l.isReady=!0}this.id=b;this.resources=[];this.entries=null;this.ast={type:"LOL",body:[]};this.isReady=!1;this.build=function(b){return!b?(g(b),f(),n(),this):g(b).then(f).then(n)};this.getEntry=
function(b){if(this.entries.hasOwnProperty(b))return this.entries[b]};var l=this}function g(b){function g(a,b){if(!z)throw new c("Context not ready");return x(0,a,b)}function u(a,b){for(var e={},c={},d,f=0,m;m=a[f];f++){Array.isArray(m)?(d=m[0],e[d]=g(m[0],m[1])):(d=m,e[d]=g(m));for(var k in e[d].globals)e[d].globals.hasOwnProperty(k)&&(c[k]=!0)}e={entities:e};b&&(b(e),h.bindGet({id:b,callback:u.bind(this,a,b),globals:Object.keys(c)}));return{}}function x(a,b,e,h){var c;c=0==q.length-a?r:B[q[a]];
if(!c)return a=new n("Entity couldn't be retrieved",b,q),D.emit("error",a),{value:h?h:b,attributes:{},globals:{}};c.isReady||c.build(!1);var d=c.getEntry(b);if(void 0===d)return D.emit("error",new l("Not found",b,c.id)),x(a+1,b,e,h);try{return d.get(E.bind(this,e))}catch(g){if(g instanceof m.Compiler.RuntimeError)return D.emit("error",new l(g.message,b,c.id)),x(a+1,b,e,h||g.source);throw g;}}function E(a){if(!a)return this.data;var b={},e;for(e in this.data)this.data.hasOwnProperty(e)&&(b[e]=this.data[e]);
if(a)for(e in a)a.hasOwnProperty(e)&&(b[e]=a[e]);return b}function C(){y=!0;for(var b=0;b<G.length;b++){var h=G[b];if("function"===typeof h){var c=void 0;for(c in B){var g=new f(h(c),a);B[c].resources.push(g)}}else{h=new f(h,a);if(0!==q.length)for(c in c=void 0,B)B[c].resources.push(h);void 0===r&&(r=new d(null,a,e));r.resources.push(h)}}return(0<q.length?B[q[0]]:r).build(!0).then(t)}function t(){z=!0;D.emit("ready");h.retranslate()}function p(a){D.emit("error",a)}this.id=b;this.data={};this.addResource=
function(b){void 0===r&&(r=new d(null,a,e));var h=new f(null,a);h.source=b;r.resources.push(h)};this.linkResource=function(a){G.push(a)};this.registerLocales=function(){if(y&&!z)throw new c("Context not ready");q=[];for(var b in arguments){var h=arguments[b];q.push(h);B[h]=new d(h,a,e)}y&&C()};this.freeze=C;this.get=function(a,b){if(!z)throw new c("Context not ready");return x(0,a,b).value};this.getEntity=g;this.localize=function(a,b){if(!z){if(!b)throw new c("Context not ready");h.bindGet({id:b,
callback:u.bind(this,a,b),globals:[]});return{}}return u(a,b)};this.addEventListener=function(b,a){D.addEventListener(b,a)};this.removeEventListener=function(b,a){D.removeEventListener(b,a)};var q=[],B={},r,G=[],y=!1,z=!1,D=new m.EventEmitter,a=new m.Parser(m.EventEmitter),e=new m.Compiler(m.EventEmitter,m.Parser),h=new m.RetranslationManager;a.addEventListener("error",p);e.addEventListener("error",p);e.setGlobals(h.globals)}function c(b){this.name="ContextError";this.message=b}function l(b,d,g){c.call(this,
b);this.name="EntityError";this.id=d;this.lang=g;this.message="["+g+"] "+d+": "+b}function n(b,d,g){c.call(this,b);this.name="GetError";this.id=d;this.tried=g;this.message=g.length?d+": "+b+"; tried "+g.join(", "):d+": "+b}var m={Context:g,getContext:function(b){return new g(b)}};g.Error=c;g.EntityError=l;c.prototype=Object.create(Error.prototype);c.prototype.constructor=c;l.prototype=Object.create(c.prototype);l.prototype.constructor=l;n.prototype=Object.create(c.prototype);n.prototype.constructor=
n;this.L20n=m}).call(this);
(function(){var f=function(){this._state=0;this._value=null;this._cb={fulfilled:[],rejected:[]};this._thenPromises=[]};f.all=function(d){function g(){l--;0==l&&c.fulfill()}var c=new f,l=d.length;if(0==l)return c.fulfill(),c;for(var n in d)d[n].then(g,g);return c};f.prototype.then=function(d,g){this._cb.fulfilled.push(d);this._cb.rejected.push(g);var c=new f;this._thenPromises.push(c);0<this._state&&setTimeout(this._processQueue.bind(this),0);return c};f.prototype.fulfill=function(d){if(0!=this._state)return this;
this._state=1;this._value=d;this._processQueue();return this};f.prototype.reject=function(d){if(0!=this._state)return this;this._state=2;this._value=d;this._processQueue();return this};f.prototype._processQueue=function(){for(;this._thenPromises.length;){var d=this._cb.fulfilled.shift(),g=this._cb.rejected.shift();this._executeCallback(1==this._state?d:g)}};f.prototype._executeCallback=function(d){var g=this._thenPromises.shift();if("function"!=typeof d)1==this._state?g.fulfill(this._value):g.reject(this._value);
else try{var c=d(this._value);c&&"function"==typeof c.then?c.then(function(c){g.fulfill(c)},function(c){g.reject(c)}):g.fulfill(c)}catch(f){g.reject(f)}};this.L20n.Promise=f}).call(this);
(function(){this.L20n.IO={load:function(f,d){return d?this.loadAsync(f):this.loadSync(f)},loadAsync:function(f){var d=new L20n.Promise,g=new XMLHttpRequest;g.overrideMimeType("text/plain");g.addEventListener("load",function(){200==g.status?d.fulfill(g.responseText):d.reject()});g.addEventListener("abort",function(c){return d.reject(c)});g.open("GET",f,!0);g.send("");return d},loadSync:function(f){new L20n.Promise;var d=new XMLHttpRequest;d.overrideMimeType("text/plain");d.open("GET",f,!1);d.send("");
return 200==d.status?d.responseText:""}}}).call(this);
(function(){function f(g){function c(){for(var a=[],e,h;;){e=u();h=[];"["===k.charAt(j)&&(++j,b(),h=v(p,"]"));b();if(":"!==k.charAt(j))throw s('Expected ":"');++j;b();e={type:void 0,key:e,value:n(),index:h};e.local="_"===e.key.name.charAt(0);a.push(e);e=m();h=k.charAt(j);if(">"===h)break;else if(!e)throw s('Expected ">"');}return a}function f(a){for(var b=a.length,e=j+b,h=k.indexOf(a,e);-1!==h&&92===k.charCodeAt(h-1)&&92!==k.charCodeAt(h-2);)h=k.indexOf(a,h+b);if(-1===h)throw s("Unclosed string literal");
a=k.slice(e,h);j=h+b;return{type:"String",content:a}}function n(a,e){void 0===e&&(e=k.charAt(j));if("'"===e||'"'===e)return e===k.charAt(j+1)&&e===k.charAt(j+2)?f(e+e+e):f(e);if("{"===e){var h;++j;b();if("}"===k.charAt(j))++j,h={type:"Hash",content:[]};else{var c,d;for(h=[];;){c=!1;if("*"===k.charAt(j)){++j;if(c)throw s("Default item redefinition forbidden");c=!0}d=u();b();if(":"!==k.charAt(j))throw s('Expected ":"');++j;b();d={type:"HashItem",key:d,value:n()};d["default"]=c;h.push(d);b();if(c=","===
k.charAt(j))++j,b();if("}"===k.charAt(j)){++j;break}if(!c)throw s('Expected "}"');}h={type:"Hash",content:h}}return h}if(!a)throw s("Unknown value type");return null}function m(){for(var a=j,b=k.charCodeAt(a);32===b||10===b||9===b||13===b;)b=k.charCodeAt(++j);return j!==a}function b(){for(var a=k.charCodeAt(j);32===a||10===a||9===a||13===a;)a=k.charCodeAt(++j)}function A(){++j;return{type:"VariableExpression",id:u()}}function u(){var a=j,b=a,e=k,h=e.charCodeAt(b);if((97>h||122<h)&&(65>h||90<h)&&95!==
h)throw s("Identifier has to start with [a-zA-Z]");for(h=e.charCodeAt(++a);95<=h&&122>=h||65<=h&&90>=h||48<=h&&57>=h||95===h;)h=e.charCodeAt(++a);j+=a-b;return{type:"Identifier",name:e.slice(b,a)}}function x(a,h){if(!m())throw s("Expected white space");var e=k.charAt(j),d=n(!0,e),w=[];if(null===d)if(">"!==e)w=c();else throw s('Expected ">"');else if(e=m(),">"!==k.charAt(j)){if(!e)throw s('Expected ">"');w=c()}b();++j;return{type:"Entity",id:a,value:d,index:h,attrs:w,local:95===a.name.charCodeAt(0)}}
function E(){var a=k.charCodeAt(j);if(60===a){++j;var e=u(),a=k.charCodeAt(j);if(40===a){if("_"===e.name.charAt(0))throw s('Macro ID cannot start with "_"');++j;a=v(A,")");m();if("{"!==k.charAt(j))throw s('Expected "{"');++j;b();var h=r();b();if("}"!==k.charAt(j))throw s('Expected "}"');++j;b();if(62!==k.charCodeAt(j))throw s('Expected ">"');++j;return{type:"Macro",id:e,args:a,expression:h}}return 91===a?(++j,x(e,v(p,"]"))):x(e,[])}if(47===k.charCodeAt(j)&&42===k.charCodeAt(j+1)){e=j+=2;a=k.indexOf("*/",
e);if(-1===a)throw s("Comment without closing tag");j=a+2;return{type:"Comment",content:k.slice(e,a)}}if("import"===k.slice(j,j+6)){j+=6;if("("!==k.charAt(j))throw s('Expected "("');++j;b();e=f(k.charAt(j));b();if(")"!==k.charAt(j))throw s('Expected ")"');++j;return{type:"ImportStatement",uri:e}}throw s("Invalid entry");}function C(){var a=[];for(b();j<F;){try{a.push(E())}catch(e){if(e instanceof d)H.emit("error",e),a.push(M());else throw e;}j<F&&b()}return{type:"LOL",body:a}}function t(){var a=[];
for(b();j<F;)a.push(E()),j<F&&b();return{type:"LOL",body:a}}function p(){return r()}function q(a,e,h,c){for(var d=c(),w,g;;){w="";b();g=k.charAt(j);if(-1===a[0].indexOf(g))break;w+=g;++j;if(1<a.length)if(g=k.charAt(j),a[1]==g)++j,w+=g;else if(a[2]){--j;break}b();d={type:e,operator:{type:h,token:w},left:d,right:c()}}return d}function B(a,e,h,c){var d=k.charCodeAt(j);if(-1===a.indexOf(d))return c();++j;b();return{type:e,operator:{type:h,token:String.fromCharCode(d)},argument:B(a,e,h,c)}}function r(){var a=
q([["|"],"|",!0],"LogicalExpression","LogicalOperator",G);b();if(63!==k.charCodeAt(j))return a;++j;b();var e=r();b();if(58!==k.charCodeAt(j))throw s('Expected ":"');++j;b();return{type:"ConditionalExpression",test:a,consequent:e,alternate:r()}}function G(){return q([["&"],"&",!0],"LogicalExpression","Logicalperator",y)}function y(){return q([["="],"=",!0],"BinaryExpression","BinaryOperator",z)}function z(){return q([["<",">"],"=",!1],"BinaryExpression","BinaryOperator",D)}function D(){return q([["+",
"-"]],"BinaryExpression","BinaryOperator",a)}function a(){return q([["%"]],"BinaryExpression","BinaryOperator",e)}function e(){return q([["*"]],"BinaryExpression","BinaryOperator",h)}function h(){return q([["/"]],"BinaryExpression","BinaryOperator",w)}function w(){return B([43,45,33],"UnaryExpression","UnaryOperator",K)}function J(a,e){if("ParenthesisExpression"!==a.type&&"CallExpression"!==a.type&&"Identifier"!==a.type&&"ThisExpression"!==a.type)throw s("AttributeExpression must have Identifier, This, Call or Parenthesis as left node");
var h;if(e){b();h=r();b();if("]"!==k.charAt(j))throw s('Expected "]"');++j;return{type:"AttributeExpression",expression:a,attribute:h,computed:!0}}h=u();return{type:"AttributeExpression",expression:a,attribute:h,computed:!1}}function K(){var a;if(40===k.charCodeAt(j)){++j;b();var e={type:"ParenthesisExpression",expression:r()};b();if(41!==k.charCodeAt(j))throw s('Expected ")"');++j;a=e}else a=L();for(;;)if(e=k.charCodeAt(j),46===e||91===e){++j;var h=void 0;if(91===e){b();h=r();b();if("]"!==k.charAt(j))throw s('Expected "]"');
++j;a={type:"PropertyExpression",expression:a,property:h,computed:!0}}else h=u(),a={type:"PropertyExpression",expression:a,property:h,computed:!1}}else if(58===e&&58===k.charCodeAt(j+1))j+=2,91===k.charCodeAt(j)?(++j,a=J(a,!0)):a=J(a,!1);else if(40===e)++j,e=a,b(),a={type:"CallExpression",callee:e,arguments:v(p,")")};else break;return a}function L(){for(var a=j,e=k.charCodeAt(a);47<e&&58>e;)e=k.charCodeAt(++a);if(a>j)return e=j,j=a,{type:"Number",value:parseInt(k.slice(e,a),10)};switch(e){case 39:case 34:case 123:case 91:return n();
case 36:return A();case 64:return++j,{type:"GlobalsExpression",id:u()};case 126:return++j,{type:"ThisExpression"};default:return u()}}function v(a,e){var h;b();if(k.charAt(j)===e)return++j,[];for(var c=[];;)if(c.push(a()),b(),h=k.charAt(j),","===h)++j,b();else if(h===e){++j;break}else throw s('Expected "," or "'+e+'"');return c}function s(a,e){void 0===e&&(e=j);var h=k.lastIndexOf("<",e-1),b=k.lastIndexOf(">",e-1),h=k.slice(b>h?b+1:h,e+10);return new d(a+" at pos "+e+': "'+h+'"',e,h)}function M(){var a=
k.indexOf("<",j),e;if(-1===a)return e={type:"JunkEntry",content:k.slice(j)},j=F,e;e={type:"JunkEntry",content:k.slice(j,a)};j=a;return e}this.parse=function(a){k=a;j=0;F=k.length;return I()};this.parseString=function(a){k=a;j=0;F=k.length;try{var e;var h,c;a=j;for(var w=!1,f=k.indexOf("\\");-1!==f;){h=k.charAt(f+1);if('"'==h||"'"==h||"\\"==h)k=k.substr(0,f)+k.substr(f+1);f=k.indexOf("\\",f+1)}for(f=k.indexOf("{{");-1!==f;)if(92===k.charCodeAt(f-1))k=k.substr(0,f-1)+k.substr(f),f=k.indexOf("{{",f+
2);else{w||(c=[],w=!0);a<f&&c.push({type:"String",content:k.slice(a,f)});j=f+2;b();c.push(r());b();if(125!==k.charCodeAt(j)||125!==k.charCodeAt(j+1))throw s('Expected "}}"');a=f=j+2;f=k.indexOf("{{",f)}w?(a<F&&c.push({type:"String",content:k.slice(a)}),e={type:"ComplexString",content:c}):e={type:"String",content:k};return e}catch(m){throw g&&m instanceof d&&H.emit("error",m),m;}};this.addEventListener=function(a,e){if(!H)throw Error("Emitter not available");return H.addEventListener(a,e)};this.removeEventListener=
function(a,e){if(!H)throw Error("Emitter not available");return H.removeEventListener(a,e)};var k,j,F,H,I;g?(H=new g,I=C):I=t}function d(d,c,f){this.name="ParserError";this.message=d;this.pos=c;this.context=f}f.Error=d;d.prototype=Object.create(Error.prototype);d.prototype.constructor=d;"undefined"!==typeof exports?exports.Parser=f:this.L20n?this.L20n.Parser=f:this.L20nParser=f}).call(this);
(function(){function f(){function c(g){g=new g;this.globals[g.id]=g;b[g.id]=0;g.addEventListener("change",function(b){for(var c=0;c<d.length;c++)d[c]&&-1!==d[c].globals.indexOf(b)&&d[c].callback()})}var d=[],b={},g=[];this.bindGet=function(c){for(var f,n=0;n<g.length;n++)if(g[n].id===c.id){f=!0;break}f||g.push(c);var l=null;for(f=0;f<d.length;f++)if(d[f]&&d[f].id===c.id){l=d[f];break}l?0==c.globals.length?delete d[f]:(c.globals.filter(function(b){return-1===l.globals.indexOf(b)}).forEach(function(c){b[c]++;
this.globals[c].activate()},this),l.globals.filter(function(b){return-1===c.globals.indexOf(b)}).forEach(function(c){b[c]--;0==b[c]&&this.globals[c].deactivate()}),l.globals=c.globals):0!=c.globals.length&&(d.push(c),c.globals.forEach(function(c){b[c]++;this.globals[c].activate()},this))};this.retranslate=function(){for(var b=0;b<g.length;b++)g[b].callback()};this.globals={};for(var l in f._constructors)c.call(this,f._constructors[l])}function d(){this.id=null;this._emitter=new L20n.EventEmitter}
function g(){function c(){g=document.body.clientWidth;b._emitter.emit("change",b.id)}d.call(this);this.id="screen";this.get=function(){g||(g=document.body.clientWidth);return{width:g}};this.activate=function(){this.isActive||(window.addEventListener("resize",c),this.isActive=!0)};this.isActive=!1;var g=null,b=this}function c(){d.call(this);this.id="os";this.get=function(){return/^MacIntel/.test(navigator.platform)?"mac":/^Linux/.test(navigator.platform)?"linux":/^Win/.test(navigatgor.platform)?"win":
"unknown"}}function l(){function c(){var d=new Date;d.getHours()!==b&&(b=d.getHours(),g._emitter.emit("change",g.id))}d.call(this);this.id="hour";this.get=function(){b||(b=(new Date).getHours());return b};this.activate=function(){this.isActive||(l=setTimeout(function(){c();l=setInterval(c,f)},f-(new Date).getTime()%f),this.isActive=!0)};this.deactivate=function(){b=null;clearInterval(l);this.isActive=!1};this.isActive=!1;var g=this,b=null,f=36E5,l=null}f._constructors=[];f.registerGlobal=function(c){f._constructors.push(c)};
d.prototype.addEventListener=function(c,d){if("change"!==c)throw"Unknown event type";this._emitter.addEventListener(c,d)};d.prototype.activate=function(){};d.prototype.deactivate=function(){};f.Global=d;g.prototype=Object.create(d.prototype);g.prototype.constructor=g;c.prototype=Object.create(d.prototype);c.prototype.constructor=c;l.prototype=Object.create(d.prototype);l.prototype.constructor=l;f.registerGlobal(g);f.registerGlobal(c);f.registerGlobal(l);this.L20n.RetranslationManager=f}).call(this);
(function(){function f(){this._listeners={}}f.prototype.emit=function(){var d=Array.prototype.slice.call(arguments),g=d.shift(),g=this._listeners[g];if(!g||!g.length)return!1;g.forEach(function(c){c.apply(this,d)},this);return!0};f.prototype.addEventListener=function(d,g){this._listeners[d]||(this._listeners[d]=[]);this._listeners[d].push(g);return this};f.prototype.removeEventListener=function(d,g){var c=this._listeners[d].indexOf(g);if(-1===c)return this;listeners.splice(c,1);return this};"undefined"!==
typeof exports?exports.EventEmitter=f:this.L20n?this.L20n.EventEmitter=f:this.L20nEventEmitter=f}).call(this);
(function(){function f(b,d){var f;function x(a,e,h,b){a=new a(e,h,b);r&&r.emit("error",a);return a}function E(a){this.id=a.id.name;this.local=a.local||!1;this.index=[];this.attributes={};this.publicAttributes=[];var e;for(e=0;e<a.index.length;e++)this.index.push(p(a.index[e],this));for(e=0;e<a.attrs.length;e++){var h=a.attrs[e];this.attributes[h.key.name]=new C(h,this);h.local||this.publicAttributes.push(h.key.name)}this.value=p(a.value,this,this.index)}function C(a,e){this.key=a.key.name;this.local=
a.local||!1;this.index=[];for(var h=0;h<a.index.length;h++)this.index.push(p(a.index[h],this));this.value=p(a.value,e,this.index);this.entity=e}function t(a){this.id=a.id.name;this.local=a.local||!1;this.expression=p(a.expression,this);this.args=a.args}function p(a,e,h){if(!a)return null;if(!D[a.type])throw x("CompilationError","Unknown expression type"+a.type);h&&(h=h.slice());return D[a.type](a,e,h)}function q(a,e,h){if(!a||"string"===typeof a||"boolean"===typeof a||"number"===typeof a)return a;
if(a._resolve)return a._resolve(h);a=a(e,h);e=a[0];a=a[1];return q(a,e,h)}function B(a,e){if("=="==a)return function(a,b){if(("number"!==typeof a||"number"!==typeof b)&&("string"!==typeof a||"string"!==typeof b))throw new c("The == operator takes two numbers or two strings",e);return a==b};if("!="==a)return function(a,b){if(("number"!==typeof a||"number"!==typeof b)&&("string"!==typeof a||"string"!==typeof b))throw new c("The != operator takes two numbers or two strings",e);return a!=b};if("<"==a)return function(a,
b){if("number"!==typeof a||"number"!==typeof b)throw new c("The < operator takes two numbers",e);return a<b};if("<="==a)return function(a,b){if("number"!==typeof a||"number"!==typeof b)throw new c("The <= operator takes two numbers",e);return a<=b};if(">"==a)return function(a,b){if("number"!==typeof a||"number"!==typeof b)throw new c("The > operator takes two numbers",e);return a>b};if(">="==a)return function(a,b){if("number"!==typeof a||"number"!==typeof b)throw new c("The >= operator takes two numbers",
e);return a>=b};if("+"==a)return function(a,b){if(("number"!==typeof a||"number"!==typeof b)&&("string"!==typeof a||"string"!==typeof b))throw new c("The + operator takes two numbers or two strings",e);return a+b};if("-"==a)return function(a,b){if("number"!==typeof a||"number"!==typeof b)throw new c("The - operator takes numbers",e);return a-b};if("*"==a)return function(a,b){if("number"!==typeof a||"number"!==typeof b)throw new c("The * operator takes numbers",e);return a*b};if("/"==a)return function(a,
b){if("number"!==typeof a||"number"!==typeof b)throw new c("The / operator takes two numbers",e);if(0==b)throw new c("Division by zero not allowed.",e);return a/b};if("%"==a)return function(a,b){if("number"!==typeof a||"number"!==typeof b)throw new c("The % operator takes two numbers",e);return a%b};throw x(g,"Unknown token: "+a,e);}this.compile=function(a){y={};for(var e={Entity:E,Macro:t},b=0,c;c=a.body[b];b++){var d=e[c.type];if(d)try{y[c.id.name]=new d(c)}catch(g){m(g)}}return y};this.setGlobals=
function(a){z=a;return!0};this.addEventListener=function(a,b){if(!r)throw Error("Emitter not available");return r.addEventListener(a,b)};this.removeEventListener=function(a,b){if(!r)throw Error("Emitter not available");return r.removeEventListener(a,b)};this.reset=function(){y={};z={};f={};return this};var r=b?new b:null,G=d?new d:null,y={},z={};f={};E.prototype._yield=function(a,b){return this.value({__this__:this},a,b)};E.prototype._resolve=function(a){return q(this.value,{__this__:this},a)};E.prototype.getString=
function(a){try{return this._resolve(a)}catch(b){throw m(b),b instanceof l&&r&&r.emit("error",b),b;}};E.prototype.get=function(a){f={};for(var b={value:this.getString(a),attributes:{}},c=0,d;d=this.publicAttributes[c];c++)b.attributes[d]=this.attributes[d].getString(a);b.globals=f;return b};C.prototype._yield=function(a,b){return this.value({__this__:this.entity},a,b)};C.prototype._resolve=function(a){return q(this.value,{__this__:this.entity},a)};C.prototype.getString=function(a){try{return this._resolve(a)}catch(b){throw m(b),
b instanceof l&&r&&r.emit("error",b),b;}};t.prototype._call=function(a,b){for(var c={__this__:this},d=0;d<this.args.length;d++)c[this.args[d].id.name]=b[d];return this.expression(c,a)};var D={Identifier:function(a,b){var h=a.name;return function(a){if(!y.hasOwnProperty(h))throw new c("Reference to an unknown entry: "+h,b);a.__this__=y[h];return[a,y[h]]}},ThisExpression:function(){return function(a){return[a,a.__this__]}},VariableExpression:function(a,b){var h=a.id.name;return function(a,d){if(a.hasOwnProperty(h))return a[h];
if(!d||!d.hasOwnProperty(h))throw new c("Reference to an unknown variable: "+h,b);return[a,d[h]]}},GlobalsExpression:function(a,b){var h=a.id.name;return function(a){if(!z)throw new c("Globals missing (tried @"+h+").",b);if(!z.hasOwnProperty(h))throw new c("Reference to an unknown global: "+h,b);f[h]=!0;return[a,z[h].get()]}},Number:function(a){return function(b){return[b,a.value]}},String:function(a,b){var c,d;return function(g,f){if(!d){try{c=G.parseString(a.content)}catch(n){throw new l("Malformed string. "+
n.message,b,a.content);}if("String"==c.type)return[g,c.content];d=p(c,b)}try{return[g,q(d,g,f)]}catch(v){throw m(v),new l(v.message,b,a.content);}}},Hash:function(a,b,c){for(var d=[],g,f=c.length?c.shift():void 0,l=0;l<a.content.length;l++){var v=a.content[l];d[v.key.name]=p(v.value,b,c);v.default&&(g=v.key.name)}return function(a,c,h){h=[h,f,g];for(var j=[],l=0;l<h.length;l++){try{var v=h[l]=q(h[l],a,c)}catch(p){throw m(p),x(n,p.message,b);}if(void 0!==v){if("string"!==typeof v)throw x(n,"Index must be a string",
b);j.push(v);if(d.hasOwnProperty(v))return[a,d[v]]}}throw x(n,j.length?'Hash key lookup failed (tried "'+j.join('", "')+'").':"Hash key lookup failed.",b);}},HashItem:p,ComplexString:function(a,b){for(var d=[],g=0;g<a.content.length;g++)d.push(p(a.content[g],b));var f=!1;return function(a,g){if(f)throw new c("Cyclic reference detected",b);f=!0;var l=[];try{for(var m=0;m<d.length;m++){var n=q(d[m],a,g);if("string"!==typeof n&&"number"!==typeof n)throw new c("Placeables must be strings or numbers",
b);l.push(n)}}finally{f=!1}return[a,l.join("")]}},UnaryExpression:function(a,b){var d;var f=a.operator.token;if("-"==f)d=function(a){if("number"!==typeof a)throw new c("The unary - operator takes a number",b);return-a};else if("+"==f)d=function(a){if("number"!==typeof a)throw new c("The unary + operator takes a number",b);return+a};else if("!"==f)d=function(a){if("boolean"!==typeof a)throw new c("The ! operator takes a boolean",b);return!a};else throw x(g,"Unknown token: "+f,b);var l=p(a.argument,
b);return function(a,b){return[a,d(q(l,a,b))]}},BinaryExpression:function(a,b){var c=p(a.left,b),d=B(a.operator.token,b),g=p(a.right,b);return function(a,b){return[a,d(q(c,a,b),q(g,a,b))]}},LogicalExpression:function(a,b){var d=p(a.left,b),f;var l=a.operator.token;if("&&"==l)f=function(a,d){if("boolean"!==typeof a||"boolean"!==typeof d)throw new c("The && operator takes two booleans",b);return a&&d};else if("||"==l)f=function(a,d){if("boolean"!==typeof a||"boolean"!==typeof d)throw new c("The || operator takes two booleans",
b);return a||d};else throw x(g,"Unknown token: "+l,b);var m=p(a.right,b);return function(a,b){return[a,f(q(d,a,b),q(m,a,b))]}},ConditionalExpression:function(a,b){var d=p(a.test,b),g=p(a.consequent,b),f=p(a.alternate,b);return function(a,l){var m=q(d,a,l);if("boolean"!==typeof m)throw new c("Conditional expressions must test a boolean",b);return!0===m?g(a,l):f(a,l)}},CallExpression:function(a,b){for(var d=p(a.callee,b),g=[],f=0;f<a.arguments.length;f++)g.push(p(a.arguments[f],b));return function(a,
f){for(var l=[],m=0;m<g.length;m++)l.push(g[m](a,f));m=d(a,f);m=m[1];if(!m._call)throw new c("Expected a macro, got a non-callable.",b);return m._call(f,l)}},PropertyExpression:function(a,b){var d=p(a.expression,b),g=a.computed?p(a.property,b):a.property.name;return function(a,f){var l=q(g,a,f),m=d(a,f);a=m[0];m=m[1];if(m._yield)return m._yield(f,l);if("function"!==typeof m){if(!m.hasOwnProperty(l))throw new c(l+" is not defined in the context data",b);return[null,m[l]]}return m(a,f,l)}},AttributeExpression:function(a,
b){var c=p(a.expression,b),d=a.computed?p(a.attribute,b):a.attribute.name;return function(a,b){var e=q(d,a,b),f=c(a,b);a=f[0];f=f[1];return[a,f.attributes[e]]}},ParenthesisExpression:function(a,b){return p(a.expression,b)}}}function d(b,c){this.name="CompilerError";this.message=b;this.entry=c.id}function g(b,c){d.call(this,b,c);this.name="CompilationError"}function c(b,c){d.call(this,b,c);this.name="RuntimeError"}function l(b,d,f){c.call(this,b,d);this.name="ValueError";this.source=f}function n(b,
d){c.call(this,b,d);this.name="IndexError"}function m(b){if(!(b instanceof d))throw b;}f.Error=d;f.CompilationError=g;f.RuntimeError=c;f.ValueError=l;f.IndexError=n;d.prototype=Object.create(Error.prototype);d.prototype.constructor=d;g.prototype=Object.create(d.prototype);g.prototype.constructor=g;c.prototype=Object.create(d.prototype);c.prototype.constructor=c;l.prototype=Object.create(c.prototype);l.prototype.constructor=l;n.prototype=Object.create(c.prototype);n.prototype.constructor=n;"undefined"!==
typeof exports?exports.Compiler=f:this.L20n?this.L20n.Compiler=f:this.L20nCompiler=f}).call(this);
(function(){this.L20n.Intl={prioritizeLocales:function(f){for(var d={localeMatcher:"lookup"},g=[navigator.language||navigator.userLanguage],c=0,l=g.length,n=void 0;c<l&&void 0===n;){var m=g[c],b=m;a:{for(var n=f,A=b;;){if(-1!==n.indexOf(A)){n=A;break a}var u=A.lastIndexOf("-");if(-1===u){n=void 0;break a}2<=u&&"-"==A[u-2]&&(u-=2);A=A.substr(0,u)}n=void 0}c+=1}g={};if(void 0!==n){if(g.locale=n,m!==b)throw"NotImplemented";}else g.locale="en-US";m=g.locale;if(g.hasOwnProperty("extension"))throw"NotImplemented";
b="-u";for(g=0;0>g;){c=(void 0)(m)[m];l=c[0];n="";if(void 0!==extensionSubtags)throw"NotImplemented";d.hasOwnProperty("key")&&(A=d.key,-1!==c.indexOf(A)&&A!==l&&(n=""),b+=n,g+=1)}2<b.length&&(d=m.substr(0,extensionIndex),m=m.substr(extensionIndex+1),m=d+b+m);d=m;m=f.indexOf(d);if(-1===m)return f;f.splice(m,1);f.unshift(d);return f}}}).call(this);
