'use strict';(function(){function e(a,c){function f(a){if(a)return n.source?(a=new k.Promise,a.fulfill(),a):k.IO.loadAsync(n.id).then(function(a){n.source=a});n.source||(n.source=k.IO.loadSync(n.id))}function l(){n.ast=c.parse(n.source)}function r(a,b){n.ast.body.filter(function(a,b){return"ImportStatement"==a.type?(p.push(b),!0):!1}).forEach(function(a){a=a.uri.content;if(!(null===n.id||"/"==a[0])){var b=n.id.split("/").slice(0,-1).join("/");b?("/"==b[b.length-1]&&(b=b.slice(0,b.length-1)),a=b+"/"+
a):a="./"+a}a=new e(a,c);n.resources.push(a)});var f=[];n.resources.forEach(function(c){f.push(c.build(a,b))});if(b)return k.Promise.all(f)}function D(){for(var a=n.resources.length-1;0<=a;a--)Array.prototype.splice.apply(n.ast.body,[p[a]||0,1].concat(n.resources[a].ast.body));n.isReady=!0}var n=this;this.id=a;this.resources=[];this.source=null;this.isReady=!1;this.ast={type:"LOL",body:[]};this.build=function(a,c){if(7<=a)throw new b("Too many nested imports.");if(c)return f(c).then(l).then(r.bind(this,
a+1,c)).then(D);f(c);l();r(a+1,c);D()};var p=[]}function c(a,b,c){function f(a){var b=[];n.resources.forEach(function(c){b.push(c.build(0,a))});if(a)return k.Promise.all(b)}function e(){n.ast.body=n.resources.reduce(function(a,b){return a.concat(b.ast.body)},n.ast.body)}function l(){n.entries=c.compile(n.ast);n.isReady=!0}this.id=a;this.resources=[];this.entries=null;this.ast={type:"LOL",body:[]};this.isReady=!1;this.build=function(a){return!a?(f(a),e(),l(),this):f(a).then(e).then(l)};this.getEntry=
function(a){if(this.entries.hasOwnProperty(a))return this.entries[a]};var n=this}function f(a){function f(h,m,a){if(!G){if(!a)throw new b("Context not ready");return this.addEventListener("ready",f.bind(this,h,m,a))}var c=A(0,h,m);a&&(a(c.value),d.registerGet({id:a,callback:f.bind(this,h,m,a),globals:c.globals}));return c.value}function t(h,m,a){if(!G){if(!a)throw new b("Context not ready");return this.addEventListener("ready",t.bind(this,h,m,a))}var c=A(0,h,m);a&&(a(c),d.registerGet({id:a,callback:t.bind(this,
h,m,a),globals:c.globals}));return c}function z(h,a){for(var s={},b=0,c;c=h[b];b++)Array.isArray(c)?s[c[0]]=t(c[0],c[1]):s[c]=t(c);var f={};Object.keys(s).forEach(function(h){Object.keys(s[h].globals).forEach(function(h){f[h]=!0})});b={entities:s,globals:Object.keys(f)};a&&(a(b),d.registerGet({id:a,callback:z.bind(this,h,a),globals:b.globals}));return b}function A(h,a,d,b){var c;c=0==q.length-h?u:C[q[h]];if(!c)return h=new l("Entity couldn't be retrieved",a,q),x.emit("error",h),{value:b?b:a,attributes:{},
globals:{}};c.isReady||c.build(!1);var f=c.getEntry(a);if(void 0===f)return x.emit("error",new r("Not found",a,c.id)),A(h+1,a,d,b);try{return f.get(D.bind(this,d))}catch(e){if(e instanceof k.Compiler.RuntimeError)return x.emit("error",new r(e.message,a,c.id)),A(h+1,a,d,b||e.source);throw e;}}function D(a){if(!a)return this.data;var d={},b;for(b in this.data)this.data.hasOwnProperty(b)&&(d[b]=this.data[b]);if(a)for(b in a)a.hasOwnProperty(b)&&(d[b]=a[b]);return d}function n(){G=!0;x.emit("ready")}
function p(a){x.emit("error",a)}this.id=a;this.data={};this.addResource=function(a){if(0===q.length)u=new c(null,y,F);else throw new b("Can't use addResource with registered languages");var d=new e(null,y);d.source=a;u.resources.push(d)};this.linkResource=function(a){if("function"===typeof a){if(0===q.length)throw new b("No registered languages");for(var d in C){var s=new e(a(d),y);C[d].resources.push(s)}return!0}a=new e(a,y);if(0!==q.length)for(s in C)C[s].resources.push(a);else void 0===u&&(u=new c(null,
y,F)),u.resources.push(a);return!0};this.registerLocales=function(){for(var a in arguments){var d=arguments[a];q.push(d);C[d]=new c(d,y,F)}};this.freeze=function(){return(0<q.length?C[q[0]]:u).build(!0).then(n)};this.get=f;this.getEntity=t;this.localize=function(a,d){if(!G)throw new b("Context not ready");return z(a,d)};this.addEventListener=function(a,d){x.addEventListener(a,d)};this.removeEventListener=function(a,d){x.removeEventListener(a,d)};var q=[],C={},u,G=!1,x=new k.EventEmitter,y=new k.Parser(k.EventEmitter),
F=new k.Compiler(k.EventEmitter,k.Parser),d=new k.GlobalsManager;y.addEventListener("error",p);F.addEventListener("error",p);F.setGlobals(d.globals)}function b(a){this.name="ContextError";this.message=a}function r(a,c,f){b.call(this,a);this.name="EntityError";this.id=c;this.lang=f;this.message="["+f+"] "+c+": "+a}function l(a,c,f){b.call(this,a);this.name="GetError";this.id=c;this.tried=f;this.message=f.length?c+": "+a+"; tried "+f.join(", "):c+": "+a}var k={Context:f,getContext:function(a){return new f(a)}};
f.Error=b;f.EntityError=r;b.prototype=Object.create(Error.prototype);b.prototype.constructor=b;r.prototype=Object.create(b.prototype);r.prototype.constructor=r;l.prototype=Object.create(b.prototype);l.prototype.constructor=l;this.L20n=k}).call(this);
(function(){var e=function(){this._state=0;this._value=null;this._cb={fulfilled:[],rejected:[]};this._thenPromises=[]};e.all=function(c){function f(){r--;0==r&&b.fulfill()}var b=new e,r=c.length;if(0==r)return b.fulfill(),b;for(var l in c)c[l].then(f,f);return b};e.prototype.then=function(c,f){this._cb.fulfilled.push(c);this._cb.rejected.push(f);var b=new e;this._thenPromises.push(b);0<this._state&&setTimeout(this._processQueue.bind(this),0);return b};e.prototype.fulfill=function(c){if(0!=this._state)return this;
this._state=1;this._value=c;this._processQueue();return this};e.prototype.reject=function(c){if(0!=this._state)return this;this._state=2;this._value=c;this._processQueue();return this};e.prototype._processQueue=function(){for(;this._thenPromises.length;){var c=this._cb.fulfilled.shift(),f=this._cb.rejected.shift();this._executeCallback(1==this._state?c:f)}};e.prototype._executeCallback=function(c){var f=this._thenPromises.shift();if("function"!=typeof c)1==this._state?f.fulfill(this._value):f.reject(this._value);
else try{var b=c(this._value);b&&"function"==typeof b.then?b.then(function(b){f.fulfill(b)},function(b){f.reject(b)}):f.fulfill(b)}catch(e){f.reject(e)}};this.L20n.Promise=e}).call(this);
(function(){this.L20n.IO={load:function(e,c){return c?this.loadAsync(e):this.loadSync(e)},loadAsync:function(e){var c=new L20n.Promise,f=new XMLHttpRequest;f.overrideMimeType("text/plain");f.addEventListener("load",function(){200==f.status?c.fulfill(f.responseText):c.reject()});f.addEventListener("abort",function(b){return c.reject(b)});f.open("GET",e,!0);f.send("");return c},loadSync:function(e){new L20n.Promise;var c=new XMLHttpRequest;c.overrideMimeType("text/plain");c.open("GET",e,!1);c.send("");
return 200==c.status?c.responseText:""}}}).call(this);
(function(){function e(f){function b(){for(var d=[],h,b;;){h=t();b=[];"["===j.charAt(g)&&(++g,a(),b=w(p,"]"));a();if(":"!==j.charAt(g))throw v('Expected ":"');++g;a();h={type:void 0,key:h,value:l(),index:b};h.local="_"===h.key.name.charAt(0);d.push(h);h=k();b=j.charAt(g);if(">"===b)break;else if(!h)throw v('Expected ">"');}return d}function e(a){for(var d=a.length,h=g+d,b=j.indexOf(a,h);-1!==b&&92===j.charCodeAt(b-1)&&92!==j.charCodeAt(b-2);)b=j.indexOf(a,b+d);if(-1===b)throw v("Unclosed string literal");
a=j.slice(h,b);g=b+d;return{type:"String",content:a}}function l(d,h){void 0===h&&(h=j.charAt(g));if("'"===h||'"'===h)return h===j.charAt(g+1)&&h===j.charAt(g+2)?e(h+h+h):e(h);if("{"===h){var b;++g;a();if("}"===j.charAt(g))++g,b={type:"Hash",content:[]};else{var c,m;for(b=[];;){c=!1;if("*"===j.charAt(g)){++g;if(c)throw v("Default item redefinition forbidden");c=!0}m=t();a();if(":"!==j.charAt(g))throw v('Expected ":"');++g;a();m={type:"HashItem",key:m,value:l()};m["default"]=c;b.push(m);a();if(c=","===
j.charAt(g))++g,a();if("}"===j.charAt(g)){++g;break}if(!c)throw v('Expected "}"');}b={type:"Hash",content:b}}return b}if(!d)throw v("Unknown value type");return null}function k(){for(var a=g,d=j.charCodeAt(a);32===d||10===d||9===d||13===d;)d=j.charCodeAt(++g);return g!==a}function a(){for(var a=j.charCodeAt(g);32===a||10===a||9===a||13===a;)a=j.charCodeAt(++g)}function B(){++g;return{type:"VariableExpression",id:t()}}function t(){var a=g,d=a,h=j,b=h.charCodeAt(d);if((97>b||122<b)&&(65>b||90<b)&&95!==
b)throw v("Identifier has to start with [a-zA-Z]");for(b=h.charCodeAt(++a);95<=b&&122>=b||65<=b&&90>=b||48<=b&&57>=b||95===b;)b=h.charCodeAt(++a);g+=a-d;return{type:"Identifier",name:h.slice(d,a)}}function z(d,h){if(!k())throw v("Expected white space");var c=j.charAt(g),m=l(!0,c),s=[];if(null===m)if(">"!==c)s=b();else throw v('Expected ">"');else if(c=k(),">"!==j.charAt(g)){if(!c)throw v('Expected ">"');s=b()}a();++g;return{type:"Entity",id:d,value:m,index:h,attrs:s,local:95===d.name.charCodeAt(0)}}
function A(){var d=j.charCodeAt(g);if(60===d){++g;var h=t(),d=j.charCodeAt(g);if(40===d){if("_"===h.name.charAt(0))throw v('Macro ID cannot start with "_"');++g;d=w(B,")");k();if("{"!==j.charAt(g))throw v('Expected "{"');++g;a();var b=u();a();if("}"!==j.charAt(g))throw v('Expected "}"');++g;a();if(62!==j.charCodeAt(g))throw v('Expected ">"');++g;return{type:"Macro",id:h,args:d,expression:b}}return 91===d?(++g,z(h,w(p,"]"))):z(h,[])}if(47===j.charCodeAt(g)&&42===j.charCodeAt(g+1)){h=g+=2;d=j.indexOf("*/",
h);if(-1===d)throw v("Comment without closing tag");g=d+2;return{type:"Comment",content:j.slice(h,d)}}if("import"===j.slice(g,g+6)){g+=6;if("("!==j.charAt(g))throw v('Expected "("');++g;a();h=e(j.charAt(g));a();if(")"!==j.charAt(g))throw v('Expected ")"');++g;return{type:"ImportStatement",uri:h}}throw v("Invalid entry");}function D(){var d=[];for(a();g<H;){try{d.push(A())}catch(h){if(h instanceof c)I.emit("error",h),d.push(M());else throw h;}g<H&&a()}return{type:"LOL",body:d}}function n(){var d=[];
for(a();g<H;)d.push(A()),g<H&&a();return{type:"LOL",body:d}}function p(){return u()}function q(d,h,b,c){for(var m=c(),s,f;;){s="";a();f=j.charAt(g);if(-1===d[0].indexOf(f))break;s+=f;++g;if(1<d.length)if(f=j.charAt(g),d[1]==f)++g,s+=f;else if(d[2]){--g;break}a();m={type:h,operator:{type:b,token:s},left:m,right:c()}}return m}function C(d,h,b,c){var m=j.charCodeAt(g);if(-1===d.indexOf(m))return c();++g;a();return{type:h,operator:{type:b,token:String.fromCharCode(m)},argument:C(d,h,b,c)}}function u(){var d=
q([["|"],"|",!0],"LogicalExpression","LogicalOperator",G);a();if(63!==j.charCodeAt(g))return d;++g;a();var h=u();a();if(58!==j.charCodeAt(g))throw v('Expected ":"');++g;a();return{type:"ConditionalExpression",test:d,consequent:h,alternate:u()}}function G(){return q([["&"],"&",!0],"LogicalExpression","Logicalperator",x)}function x(){return q([["="],"=",!0],"BinaryExpression","BinaryOperator",y)}function y(){return q([["<",">"],"=",!1],"BinaryExpression","BinaryOperator",F)}function F(){return q([["+",
"-"]],"BinaryExpression","BinaryOperator",d)}function d(){return q([["%"]],"BinaryExpression","BinaryOperator",h)}function h(){return q([["*"]],"BinaryExpression","BinaryOperator",m)}function m(){return q([["/"]],"BinaryExpression","BinaryOperator",s)}function s(){return C([43,45,33],"UnaryExpression","UnaryOperator",J)}function L(d,h){if("ParenthesisExpression"!==d.type&&"CallExpression"!==d.type&&"Identifier"!==d.type&&"ThisExpression"!==d.type)throw v("AttributeExpression must have Identifier, This, Call or Parenthesis as left node");
var b;if(h){a();b=u();a();if("]"!==j.charAt(g))throw v('Expected "]"');++g;return{type:"AttributeExpression",expression:d,attribute:b,computed:!0}}b=t();return{type:"AttributeExpression",expression:d,attribute:b,computed:!1}}function J(){var d;if(40===j.charCodeAt(g)){++g;a();var h={type:"ParenthesisExpression",expression:u()};a();if(41!==j.charCodeAt(g))throw v('Expected ")"');++g;d=h}else d=E();for(;;)if(h=j.charCodeAt(g),46===h||91===h){++g;var b=void 0;if(91===h){a();b=u();a();if("]"!==j.charAt(g))throw v('Expected "]"');
++g;d={type:"PropertyExpression",expression:d,property:b,computed:!0}}else b=t(),d={type:"PropertyExpression",expression:d,property:b,computed:!1}}else if(58===h&&58===j.charCodeAt(g+1))g+=2,91===j.charCodeAt(g)?(++g,d=L(d,!0)):d=L(d,!1);else if(40===h)++g,h=d,a(),d={type:"CallExpression",callee:h,arguments:w(p,")")};else break;return d}function E(){for(var d=g,a=j.charCodeAt(d);47<a&&58>a;)a=j.charCodeAt(++d);if(d>g)return a=g,g=d,{type:"Number",value:parseInt(j.slice(a,d),10)};switch(a){case 39:case 34:case 123:case 91:return l();
case 36:return B();case 64:return++g,{type:"GlobalsExpression",id:t()};case 126:return++g,{type:"ThisExpression"};default:return t()}}function w(d,h){var b;a();if(j.charAt(g)===h)return++g,[];for(var c=[];;)if(c.push(d()),a(),b=j.charAt(g),","===b)++g,a();else if(b===h){++g;break}else throw v('Expected "," or "'+h+'"');return c}function v(d,a){void 0===a&&(a=g);var h=j.lastIndexOf("<",a-1),b=j.lastIndexOf(">",a-1),h=j.slice(b>h?b+1:h,a+10);return new c(d+" at pos "+a+': "'+h+'"',a,h)}function M(){var d=
j.indexOf("<",g),a;if(-1===d)return a={type:"JunkEntry",content:j.slice(g)},g=H,a;a={type:"JunkEntry",content:j.slice(g,d)};g=d;return a}this.parse=function(d){j=d;g=0;H=j.length;return K()};this.parseString=function(d){j=d;g=0;H=j.length;try{var h;var b,m;d=g;for(var s=!1,e=j.indexOf("\\");-1!==e;){b=j.charAt(e+1);if('"'==b||"'"==b||"\\"==b)j=j.substr(0,e)+j.substr(e+1);e=j.indexOf("\\",e+1)}for(e=j.indexOf("{{");-1!==e;)if(92===j.charCodeAt(e-1))j=j.substr(0,e-1)+j.substr(e),e=j.indexOf("{{",e+
2);else{s||(m=[],s=!0);d<e&&m.push({type:"String",content:j.slice(d,e)});g=e+2;a();m.push(u());a();if(125!==j.charCodeAt(g)||125!==j.charCodeAt(g+1))throw v('Expected "}}"');d=e=g+2;e=j.indexOf("{{",e)}s?(d<H&&m.push({type:"String",content:j.slice(d)}),h={type:"ComplexString",content:m}):h={type:"String",content:j};return h}catch(k){throw f&&k instanceof c&&I.emit("error",k),k;}};this.addEventListener=function(d,a){if(!I)throw Error("Emitter not available");return I.addEventListener(d,a)};this.removeEventListener=
function(d,a){if(!I)throw Error("Emitter not available");return I.removeEventListener(d,a)};var j,g,H,I,K;f?(I=new f,K=D):K=n}function c(c,b,e){this.name="ParserError";this.message=c;this.pos=b;this.context=e}e.Error=c;c.prototype=Object.create(Error.prototype);c.prototype.constructor=c;"undefined"!==typeof exports?exports.Parser=e:this.L20n?this.L20n.Parser=e:this.L20nParser=e}).call(this);
(function(){var e=function(){function b(e){e=new e;c[e.id]=e;f[e.id]=0;e.addEventListener("change",function(b){for(var c=0;c<a.length;c++)-1!==a[c].globals.indexOf(b)&&a[c].callback()})}var c={},a=[],f={};this.registerGlobal=b;this.registerGet=function(b){for(var e=null,l=0;l<a.length;l++)if(a[l].id===b.id){e=a[l];break}e?0==b.globals.length?delete a[l]:(b.globals.filter(function(a){return-1===e.globals.indexOf(a)}).forEach(function(a){f[a]++;c[a].activate()}),e.globals.filter(function(a){return-1===
b.globals.indexOf(a)}).forEach(function(a){f[a]--;0==f[a]&&c[a].deactivate()}),e.globals=b.globals):0!=b.globals.length&&(a.push(b),b.globals.forEach(function(a){f[a]++;c[a].activate()}))};this.globals=c;for(var t in e._constructors)b(e._constructors[t])};e._constructors=[];e.registerGlobal=function(b){e._constructors.push(b)};var c=function(){this.id=null;this._emitter=new L20n.EventEmitter};c.prototype.addEventListener=function(b,c){if("change"!==b)throw"Unknown event type";this._emitter.addEventListener(b,
c)};c.prototype.activate=function(){};c.prototype.deactivate=function(){};e.Global=c;L20n.GlobalsManager=e;var f=function(){function b(){e=document.body.clientWidth;a._emitter.emit("change",a.id)}c.call(this);this.id="screen";this.get=function(){e||(e=document.body.clientWidth);return{width:e}};this.activate=function(){this.isActive||(window.addEventListener("resize",b),this.isActive=!0)};this.isActive=!1;var e=null,a=this};f.prototype=Object.create(c.prototype);f.prototype.constructor=f;var b=function(){c.call(this);
this.id="os";this.get=function(){return/^MacIntel/.test(navigator.platform)?"mac":/^Linux/.test(navigator.platform)?"linux":/^Win/.test(navigatgor.platform)?"win":"unknown"}};b.prototype=Object.create(c.prototype);b.prototype.constructor=b;var r=function(){function b(){var c=new Date;c.getHours()!==a&&(a=c.getHours(),e._emitter.emit("change",e.id))}c.call(this);this.id="hour";this.get=function(){a||(a=(new Date).getHours());return a};this.activate=function(){this.isActive||(t=setTimeout(function(){b();
t=setInterval(b,f)},f-(new Date).getTime()%f),this.isActive=!0)};this.deactivate=function(){a=null;clearInterval(t);this.isActive=!1};this.isActive=!1;var e=this,a=null,f=36E5,t=null};r.prototype=Object.create(c.prototype);r.prototype.constructor=r;e.registerGlobal(f);e.registerGlobal(b);e.registerGlobal(r)}).call(this);
(function(){function e(){this._listeners={}}e.prototype.emit=function(){var c=Array.prototype.slice.call(arguments),e=c.shift(),e=this._listeners[e];if(!e||!e.length)return!1;e.forEach(function(b){b.apply(this,c)},this);return!0};e.prototype.addEventListener=function(c,e){this._listeners[c]||(this._listeners[c]=[]);this._listeners[c].push(e);return this};e.prototype.removeEventListener=function(c,e){var b=this._listeners[c].indexOf(e);if(-1===b)return this;listeners.splice(b,1);return this};"undefined"!==
typeof exports?exports.EventEmitter=e:this.L20n?this.L20n.EventEmitter=e:this.L20nEventEmitter=e}).call(this);
(function(){function e(a,c){var e;function z(d,a,b,c){d=new d(a,b,c);u&&u.emit("error",d);return d}function A(d){this.id=d.id.name;this.local=d.local||!1;this.index=[];this.attributes={};this.publicAttributes=[];var a;for(a=0;a<d.index.length;a++)this.index.push(p(d.index[a],this));for(a=0;a<d.attrs.length;a++){var b=d.attrs[a];this.attributes[b.key.name]=new D(b,this);b.local||this.publicAttributes.push(b.key.name)}this.value=p(d.value,this,this.index)}function D(d,a){this.key=d.key.name;this.local=
d.local||!1;this.index=[];for(var b=0;b<d.index.length;b++)this.index.push(p(d.index[b],this));this.value=p(d.value,a,this.index);this.entity=a}function n(a){this.id=a.id.name;this.local=a.local||!1;this.expression=p(a.expression,this);this.args=a.args}function p(a,b,c){if(!a)return null;if(!F[a.type])throw z("CompilationError","Unknown expression type"+a.type);c&&(c=c.slice());return F[a.type](a,b,c)}function q(a,b,c){if(!a||"string"===typeof a||"boolean"===typeof a||"number"===typeof a)return a;
if(a._resolve)return a._resolve(c);a=a(b,c);b=a[0];a=a[1];return q(a,b,c)}function C(a,h){if("=="==a)return function(a,d){if(("number"!==typeof a||"number"!==typeof d)&&("string"!==typeof a||"string"!==typeof d))throw new b("The == operator takes two numbers or two strings",h);return a==d};if("!="==a)return function(a,d){if(("number"!==typeof a||"number"!==typeof d)&&("string"!==typeof a||"string"!==typeof d))throw new b("The != operator takes two numbers or two strings",h);return a!=d};if("<"==a)return function(a,
d){if("number"!==typeof a||"number"!==typeof d)throw new b("The < operator takes two numbers",h);return a<d};if("<="==a)return function(a,d){if("number"!==typeof a||"number"!==typeof d)throw new b("The <= operator takes two numbers",h);return a<=d};if(">"==a)return function(a,d){if("number"!==typeof a||"number"!==typeof d)throw new b("The > operator takes two numbers",h);return a>d};if(">="==a)return function(a,d){if("number"!==typeof a||"number"!==typeof d)throw new b("The >= operator takes two numbers",
h);return a>=d};if("+"==a)return function(a,d){if(("number"!==typeof a||"number"!==typeof d)&&("string"!==typeof a||"string"!==typeof d))throw new b("The + operator takes two numbers or two strings",h);return a+d};if("-"==a)return function(a,d){if("number"!==typeof a||"number"!==typeof d)throw new b("The - operator takes numbers",h);return a-d};if("*"==a)return function(a,d){if("number"!==typeof a||"number"!==typeof d)throw new b("The * operator takes numbers",h);return a*d};if("/"==a)return function(a,
d){if("number"!==typeof a||"number"!==typeof d)throw new b("The / operator takes two numbers",h);if(0==d)throw new b("Division by zero not allowed.",h);return a/d};if("%"==a)return function(a,d){if("number"!==typeof a||"number"!==typeof d)throw new b("The % operator takes two numbers",h);return a%d};throw z(f,"Unknown token: "+a,h);}this.compile=function(a){x={};for(var b={Entity:A,Macro:n},c=0,e;e=a.body[c];c++){var f=b[e.type];if(f)try{x[e.id.name]=new f(e)}catch(l){k(l)}}return x};this.setGlobals=
function(a){y=a;return!0};this.addEventListener=function(a,b){if(!u)throw Error("Emitter not available");return u.addEventListener(a,b)};this.removeEventListener=function(a,b){if(!u)throw Error("Emitter not available");return u.removeEventListener(a,b)};this.reset=function(){x={};y={};e={};return this};var u=a?new a:null,G=c?new c:null,x={},y={};e={};A.prototype._yield=function(a,b){return this.value({__this__:this},a,b)};A.prototype._resolve=function(a){return q(this.value,{__this__:this},a)};A.prototype.getString=
function(a){try{return this._resolve(a)}catch(b){throw k(b),b instanceof r&&u&&u.emit("error",b),b;}};A.prototype.get=function(a){e={};for(var b={value:this.getString(a),attributes:{}},c=0,f;f=this.publicAttributes[c];c++)b.attributes[f]=this.attributes[f].getString(a);b.globals=e;return b};D.prototype._yield=function(a,b){return this.value({__this__:this.entity},a,b)};D.prototype._resolve=function(a){return q(this.value,{__this__:this.entity},a)};D.prototype.getString=function(a){try{return this._resolve(a)}catch(b){throw k(b),
b instanceof r&&u&&u.emit("error",b),b;}};n.prototype._call=function(a,b){for(var c={__this__:this},e=0;e<this.args.length;e++)c[this.args[e].id.name]=b[e];return this.expression(c,a)};var F={Identifier:function(a,c){var e=a.name;return function(a){if(!x.hasOwnProperty(e))throw new b("Reference to an unknown entry: "+e,c);a.__this__=x[e];return[a,x[e]]}},ThisExpression:function(){return function(a){return[a,a.__this__]}},VariableExpression:function(a,c){var e=a.id.name;return function(a,d){if(a.hasOwnProperty(e))return a[e];
if(!d||!d.hasOwnProperty(e))throw new b("Reference to an unknown variable: "+e,c);return[a,d[e]]}},GlobalsExpression:function(a,c){var f=a.id.name;return function(a){if(!y)throw new b("Globals missing (tried @"+f+").",c);if(!y.hasOwnProperty(f))throw new b("Reference to an unknown global: "+f,c);e[f]=!0;return[a,y[f].get()]}},Number:function(a){return function(b){return[b,a.value]}},String:function(a,b){var c,e;return function(f,l){if(!e){try{c=G.parseString(a.content)}catch(E){throw new r("Malformed string. "+
E.message,b,a.content);}if("String"==c.type)return[f,c.content];e=p(c,b)}try{return[f,q(e,f,l)]}catch(w){throw k(w),new r(w.message,b,a.content);}}},Hash:function(a,b,c){for(var e=[],f,J=c.length?c.shift():void 0,E=0;E<a.content.length;E++){var w=a.content[E];e[w.key.name]=p(w.value,b,c);w.default&&(f=w.key.name)}return function(a,d,c){c=[c,J,f];for(var g=[],m=0;m<c.length;m++){try{var w=c[m]=q(c[m],a,d)}catch(E){throw k(E),z(l,E.message,b);}if(void 0!==w){if("string"!==typeof w)throw z(l,"Index must be a string",
b);g.push(w);if(e.hasOwnProperty(w))return[a,e[w]]}}throw z(l,g.length?'Hash key lookup failed (tried "'+g.join('", "')+'").':"Hash key lookup failed.",b);}},HashItem:p,ComplexString:function(a,c){for(var e=[],f=0;f<a.content.length;f++)e.push(p(a.content[f],c));var l=!1;return function(a,d){if(l)throw new b("Cyclic reference detected",c);l=!0;var f=[];try{for(var s=0;s<e.length;s++){var k=q(e[s],a,d);if("string"!==typeof k&&"number"!==typeof k)throw new b("Placeables must be strings or numbers",
c);f.push(k)}}finally{l=!1}return[a,f.join("")]}},UnaryExpression:function(a,c){var e;var l=a.operator.token;if("-"==l)e=function(a){if("number"!==typeof a)throw new b("The unary - operator takes a number",c);return-a};else if("+"==l)e=function(a){if("number"!==typeof a)throw new b("The unary + operator takes a number",c);return+a};else if("!"==l)e=function(a){if("boolean"!==typeof a)throw new b("The ! operator takes a boolean",c);return!a};else throw z(f,"Unknown token: "+l,c);var k=p(a.argument,
c);return function(a,b){return[a,e(q(k,a,b))]}},BinaryExpression:function(a,b){var c=p(a.left,b),e=C(a.operator.token,b),f=p(a.right,b);return function(a,b){return[a,e(q(c,a,b),q(f,a,b))]}},LogicalExpression:function(a,c){var e=p(a.left,c),l;var k=a.operator.token;if("&&"==k)l=function(a,d){if("boolean"!==typeof a||"boolean"!==typeof d)throw new b("The && operator takes two booleans",c);return a&&d};else if("||"==k)l=function(a,d){if("boolean"!==typeof a||"boolean"!==typeof d)throw new b("The || operator takes two booleans",
c);return a||d};else throw z(f,"Unknown token: "+k,c);var n=p(a.right,c);return function(a,b){return[a,l(q(e,a,b),q(n,a,b))]}},ConditionalExpression:function(a,c){var e=p(a.test,c),f=p(a.consequent,c),l=p(a.alternate,c);return function(a,d){var k=q(e,a,d);if("boolean"!==typeof k)throw new b("Conditional expressions must test a boolean",c);return!0===k?f(a,d):l(a,d)}},CallExpression:function(a,c){for(var e=p(a.callee,c),f=[],l=0;l<a.arguments.length;l++)f.push(p(a.arguments[l],c));return function(a,
d){for(var l=[],k=0;k<f.length;k++)l.push(f[k](a,d));k=e(a,d);k=k[1];if(!k._call)throw new b("Expected a macro, got a non-callable.",c);return k._call(d,l)}},PropertyExpression:function(a,c){var e=p(a.expression,c),f=a.computed?p(a.property,c):a.property.name;return function(a,d){var l=q(f,a,d),k=e(a,d);a=k[0];k=k[1];if(k._yield)return k._yield(d,l);if("function"!==typeof k){if(!k.hasOwnProperty(l))throw new b(l+" is not defined in the context data",c);return[null,k[l]]}return k(a,d,l)}},AttributeExpression:function(a,
b){var c=p(a.expression,b),e=a.computed?p(a.attribute,b):a.attribute.name;return function(a,b){var d=q(e,a,b),f=c(a,b);a=f[0];f=f[1];return[a,f.attributes[d]]}},ParenthesisExpression:function(a,b){return p(a.expression,b)}}}function c(a,b){this.name="CompilerError";this.message=a;this.entry=b.id}function f(a,b){c.call(this,a,b);this.name="CompilationError"}function b(a,b){c.call(this,a,b);this.name="RuntimeError"}function r(a,c,e){b.call(this,a,c);this.name="ValueError";this.source=e}function l(a,
c){b.call(this,a,c);this.name="IndexError"}function k(a){if(!(a instanceof c))throw a;}e.Error=c;e.CompilationError=f;e.RuntimeError=b;e.ValueError=r;e.IndexError=l;c.prototype=Object.create(Error.prototype);c.prototype.constructor=c;f.prototype=Object.create(c.prototype);f.prototype.constructor=f;b.prototype=Object.create(c.prototype);b.prototype.constructor=b;r.prototype=Object.create(b.prototype);r.prototype.constructor=r;l.prototype=Object.create(b.prototype);l.prototype.constructor=l;"undefined"!==
typeof exports?exports.Compiler=e:this.L20n?this.L20n.Compiler=e:this.L20nCompiler=e}).call(this);
(function(){this.L20n.Intl={prioritizeLocales:function(e){for(var c={localeMatcher:"lookup"},f=[navigator.language||navigator.userLanguage],b=0,r=f.length,l=void 0;b<r&&void 0===l;){var k=f[b],a=k;a:{for(var l=e,B=a;;){if(-1!==l.indexOf(B)){l=B;break a}var t=B.lastIndexOf("-");if(-1===t){l=void 0;break a}2<=t&&"-"==B[t-2]&&(t-=2);B=B.substr(0,t)}l=void 0}b+=1}f={};if(void 0!==l){if(f.locale=l,k!==a)throw"NotImplemented";}else f.locale="en-US";k=f.locale;if(f.hasOwnProperty("extension"))throw"NotImplemented";
a="-u";for(f=0;0>f;){b=(void 0)(k)[k];r=b[0];l="";if(void 0!==extensionSubtags)throw"NotImplemented";c.hasOwnProperty("key")&&(B=c.key,-1!==b.indexOf(B)&&B!==r&&(l=""),a+=l,f+=1)}2<a.length&&(c=k.substr(0,extensionIndex),k=k.substr(extensionIndex+1),k=c+a+k);c=k;k=e.indexOf(c);if(-1===k)return e;e.splice(k,1);e.unshift(c);return e}}}).call(this);
