/*
 MIT License (c) copyright B Cavalier & J Hann */
'use strict';function l(c){throw c;}var w=void 0,y=!0,A=null,C=!1;
("function"==typeof define&&define.ha?define:function(c){"object"===typeof exports?module.oa=c():this.xa=c()})(function(){function c(b,s,a,c){return d(b).b(s,a,c)}function d(b){var s,a;b instanceof e?s=b:g(b)?(a=p(),b.b(function(b){a.a(b)},function(b){a.i(b)},function(b){a.m(b)}),s=a.j):s=new e(function(a){try{return d(a?a(b):b)}catch(s){return k(s)}});return s}function e(b){this.b=b}function k(b){return new e(function(a,m){try{return m?d(m(b)):k(b)}catch(c){return k(c)}})}function p(){function b(b,
a,s){return n(b,a,s)}function s(b){return r(b)}function m(b){return r(k(b))}function c(b){return q(b)}var N,g,f,n,q,r;N={b:b,a:s,i:m,m:c,j:new e(b),va:{a:s,i:m,m:c}};g=[];f=[];n=function(b,a,s){var m,c;m=p();c="function"===typeof s?function(b){try{m.m(s(b))}catch(a){m.m(a)}}:function(b){m.m(b)};g.push(function(s){s.b(b,a).b(m.a,m.i,c)});f.push(c);return m.j};q=function(b){u(f,b);return b};r=function(b){b=d(b);n=b.b;r=d;q=B;u(g,b);f=g=a;return b};return N}function g(b){return b&&"function"===typeof b.b}
function f(b,a,m,d,e){v(2,arguments);return c(b,function(b){function g(b){u(b)}function k(b){x(b)}var f,n,q,r,z,x,u,j,h,v;h=b.length>>>0;f=Math.max(0,Math.min(a,h));q=[];n=h-f+1;r=[];z=p();if(f){j=z.m;u=function(b){r.push(b);--n||(x=u=B,z.i(r))};x=function(b){q.push(b);--f||(x=u=B,z.a(q))};for(v=0;v<h;++v)v in b&&c(b[v],k,g,j)}else z.a(q);return z.b(m,d,e)})}function n(b,a){return c(b,function(b){var d,e,g,k,f,q;g=e=b.length>>>0;d=[];q=p();if(g){k=function(b,m){c(b,a).b(function(b){d[m]=b;--g||q.a(d)},
q.i)};for(f=0;f<e;f++)f in b?k(b[f],f):--g}else q.a(d);return q.j})}function u(b,a){for(var m,c=0;m=b[c++];)m(a)}function v(b,a){for(var m,c=a.length;c>b;)m=a[--c],m!=A&&"function"!=typeof m&&l(Error("arg "+c+" must be a function"))}function B(){}function q(b){return b}var z,r,a;c.defer=p;c.a=d;c.i=function(b){return c(b,k)};c.join=function(){return n(arguments,q)};c.all=function(b,a,m,c){v(1,arguments);return n(b,q).b(a,m,c)};c.map=n;c.reduce=function(b,a){var m=r.call(arguments,1);return c(b,function(b){var d;
d=b.length;m[0]=function(b,m,e){return c(b,function(b){return c(m,function(m){return a(b,m,e,d)})})};return z.apply(b,m)})};c.ia=function(b,a,m,c){return f(b,1,function(b){return a?a(b[0]):b[0]},m,c)};c.some=f;c.ja=function(b,a,m){var d=2<arguments.length;return c(b,function(b){b=d?m:b;a.a(b);return b},function(b){a.i(b);return k(b)},a.m)};c.sa=g;e.prototype={};r=[].slice;z=[].reduce||function(b){var a,m,c,d,e;e=0;a=Object(this);d=a.length>>>0;m=arguments;if(1>=m.length)for(;;){if(e in a){c=a[e++];
break}++e>=d&&l(new TypeError)}else c=m[1];for(;e<d;++e)e in a&&(c=b(c,a[e],e,a));return c};return c});function D(c,d){this.text=d;this.g=A;this.url=c}
function E(c,d,e){function k(c){var d=n.source.url.split("/").slice(0,-1).join("/");return"/"==c[0]?c:d?("/"==d[d.length-1]&&(d=d.slice(0,d.length-1)),d+"/"+c):"./"+c}function p(c,e){var g=when.defer(),f=F(c,d.e.d[0],d.e.c[e]);n.source&&(f=k(f));I.B.N(f).b(function(a){g.a(new D(f,a))},function(){if(d.e.c.length>=e+1)p(c,e+1).b(function(a){return g.a(a)},function(){return g.a()});else return g.a()});return g.j}function g(c,e){var f=F(c,d.e.d[0],d.e.c[e]);n.source&&(f=k(f));var r=A;return d.e.c.length>=
e+1||0===d.e.c.length&&0===e?(r=I.B.V(f))?new D(f,r):g(c,e+1):C}function f(c,f,k){if(7<k)return C;var r=new E(c,d,e);n.k.push(r);if(f){var a=when.defer();u.push(a);p(c,0).b(function(b){b&&(r.source=b,r.parse(y,k))}).b(function(){a.a(r)})}else r.source=g(c,0),r.parse(C,k)}var n=this;this.id=c;this.k=[];this.source=A;this.o=C;this.g={type:"LOL",body:[]};this.L=function(){var c=when.defer();when.all(u).b(function(){var d=[];n.k.forEach(function(c){d.push(c.L())});when.all(d).b(function(){for(var d=0,
e;e=n.k[d];d++){var a=v[d];e.source&&(n.source===A?n.g.body=n.g.body.concat(e.source.g.body):Array.prototype.splice.apply(n.g.body,[a,1].concat(e.source.g.body)))}n.o=y;return c.a()})});return c.j};this.v=function(c,g){var f=new E(c,d,e),k=new D(c,g);f.source=k;k.g=e.parse(k.text);this.k.push(f);v.push(0)};this.r=f;this.parse=function(c,d){this.g=this.source.g=e.parse(this.source.text);this.source.g.body.filter(function(c,d){return"ImportStatement"==c.type?(v.push(d),y):C}).forEach(function(e){f(e.uri.content,
c,d+1)})};var u=[],v=[]}
function J(c){function d(b,a){B.o||l("Error: context not ready");if(!q.hasOwnProperty(b)||q[b].f===y)return f("Missing entity",b),e(b,a);var c=q[b],d=k(a);try{return c.toString(d)}catch(g){return f("Entity could not be resolved",b),e(b,a,g.source)}}function e(b,s,m){var d;if(2>a.d.length)d=A;else{if(r===A){r=new J(self);r.e.d=a.d.slice(1);r.addEventListener("error",g);a.c.length&&(r.e.c=a.c);for(d in B.k)B.k[d].id===A?r.v(A,B.k[d].source.text):r.r(B.k[d].id,C);r.freeze()}d=r}var e=A;d?e=d.get(b,s):
f("No more locale fallbacks",b);return c||e!==A?e:m?m:b}function k(b){if(!b)return z;var a={},c;for(c in z)z.hasOwnProperty(c)&&(a[c]=z[c]);if(b)for(c in b)b.hasOwnProperty(c)&&(a[c]=b[c]);return a}function p(b,a){var c={},e;for(e in b)c[b[e]]=d(b[e],a);return c}function g(b){n.l("error",b)}function f(b,c){n.l("error",new K(b,c,a.d[0]))}this.Z=K;this.data={};this.o=this.isFrozen=A;this.v=function(b,a){B.v(b,a);return this};this.r=function(b,a){a===w&&(a=y);B.r(b,a,0);return this};this.freeze=function(){B.L().b(function(){q=
v.compile(B.g);n.l("ready")});return this};this.get=d;this.T=function(b,a){B.o||l("Error: context not ready");(!q.hasOwnProperty(b)||q[b].f===y)&&l("Missing entity: "+b);var c=q[b],d=k(a),e={},g;for(g in c.attributes){var f=c.attributes[g];f.f||(e[g]=f.toString(d))}return{value:c.toString(d),attributes:e}};this.getAttribute=function(b,a,c){B.o||l("Error: context not ready");(!q.hasOwnProperty(b)||q[b].f===y)&&l("Missing entity: "+b);b=q[b];(!b.attributes.hasOwnProperty(a)||b.attributes[a].f===y)&&
l("No such attribute: "+a);return b.attributes[a].toString(k(c))};this.qa=function(b,a){var c=when.defer();if(B.o){var d=p(b,a);c.a(d)}else setTimeout(function(){c.i()},500),self.addEventListener("ready",function(){var d=p(b,a);c.a(d)});return c.j};this.pa=A;this.addEventListener=function(b,a){n.addEventListener(b,a)};this.removeEventListener=function(b,a){n.removeEventListener(b,a)};var n=new I.A,u=new I.C(I.A),v=new I.H(I.A,I.C),B=new E(A,this,u),q={},z={},r=A,a={locales:[],schemes:[],timeout:500};
u.addEventListener("error",g);v.addEventListener("error",g);v.X({get ra(){return(new Date).getHours()},get ta(){return/^MacIntel/.test(navigator.platform)?"mac":/^Linux/.test(navigator.platform)?"linux":/^Win/.test(navigatgor.platform)?"win":"unknown"},screen:{get width(){return document.body.clientWidth},get height(){return document.body.clientHeight}}});this.__defineSetter__("data",function(b){z=b});this.__defineGetter__("data",function(){return z});Object.defineProperty(this,"settings",{value:Object.create(Object.prototype,
{d:{get:function(){return a.d},set:function(b){Array.isArray(b)||l("Locales must be a list");0==b.length&&l("Locales list must not be empty");0<a.d.length&&l("Can't overwrite locales");a.d=b;Object.freeze(a.d)},configurable:C,enumerable:y},c:{get:function(){return a.c},set:function(b){Array.isArray(b)||l("Schemes must be a list");0==b.length&&l("Scheme list must not be empty");0<a.c.length&&l("Can't overwrite schemes");a.c=b;Object.freeze(a.c)},configurable:C,enumerable:y},timeout:{get:function(){return a.timeout},
set:function(b){"number"!==typeof b&&l("Timeout must be a number");a.timeout=b},configurable:C,enumerable:y}}),writable:C,enumerable:C,configurable:C})}function aa(c,d){return c.replace(/(\{\{\s*(\w+)\s*\}\})/g,function(c,k,p){if(d.hasOwnProperty(p))return d[p];l("Cannot use the undefined variable: "+p)})}
function F(c,d,e){if(!/^l10n:/.test(c))return c;var k=c.match(/^l10n:(?:([^:]+):)?([^:]+)/);k===A&&l("Malformed resource scheme: "+c);k[2]&&"/"==k[2][0]&&"/"==k[2][1]?(c=k[0].substring(5),k=""):(c=k[2],k=k[1]);var p={app:k,resource:c};d&&(p.locale=d);if(!e)return k&&l("You need to define schemes to use with app uris"),aa(c,p);e=e.substr(5);return aa(e,p)}function K(c,d,e){this.name="ContextError";this.id=d;this.locale=e;this.message=c+", locale: "+e+", id: "+d}var I={getContext:function(){return new J}};
K.prototype=Object.create(Error.prototype);this.t=I;L20n.B={N:function(c){var d=when.defer(),e=new XMLHttpRequest;e.overrideMimeType("text/plain");e.addEventListener("load",function(){200==e.status?d.a(e.responseText):d.i()});e.addEventListener("abort",function(c){return when.i(c)});e.open("GET",c,y);e.send("");return d.j},V:function(c){var d=new XMLHttpRequest;d.overrideMimeType("text/plain");d.open("GET",c,C);d.send("");return 200==d.status?d.responseText:C}};
function L(c){function d(){for(var b=[],a,c;!(a=n(),c=[],"["===j.charAt(h)&&(++h,g(),c=O(z,"]")),g(),":"!==j.charAt(h)&&l(x('Expected ":"')),++h,g(),a={type:w,key:a,value:k(),index:c},a.f="_"===a.key.name.charAt(0),b.push(a),a=p(),c=j.charAt(h),">"===c);)a||l(x('Expected ">"'));return b}function e(b){for(var a=b.length,c=h+a,d=j.indexOf(b,c);-1!==d&&92===j.charCodeAt(d-1)&&92!==j.charCodeAt(d-2);)d=j.indexOf(b,d+a);-1===d&&l(x("Unclosed string literal"));b=j.slice(c,d);h=d+a;return{type:"String",
content:b}}function k(b,a){a===w&&(a=j.charAt(h));if("'"===a||'"'===a)return a===j.charAt(h+1)&&a===j.charAt(h+2)?e(a+a+a):e(a);if("{"===a){var c;++h;g();if("}"===j.charAt(h))++h,c={type:"Hash",content:[]};else{var d,m;for(c=[];;){d=C;"*"===j.charAt(h)&&(++h,d&&l(x("Default item redefinition forbidden")),d=y);m=n();g();":"!==j.charAt(h)&&l(x('Expected ":"'));++h;g();m={type:"HashItem",key:m,value:k()};m["default"]=d;c.push(m);g();if(d=","===j.charAt(h))++h,g();if("}"===j.charAt(h)){++h;break}d||l(x('Expected "}"'))}c=
{type:"Hash",content:c}}return c}b||l(x("Unknown value type"));return A}function p(){for(var b=h,a=j.charCodeAt(b);32===a||10===a||9===a||13===a;)a=j.charCodeAt(++h);return h!==b}function g(){for(var b=j.charCodeAt(h);32===b||10===b||9===b||13===b;)b=j.charCodeAt(++h)}function f(){++h;return{type:"VariableExpression",id:n()}}function n(){var b=h,a=b,c=j,d=c.charCodeAt(a);(97>d||122<d)&&((65>d||90<d)&&95!==d)&&l(x("Identifier has to start with [a-zA-Z]"));for(d=c.charCodeAt(++b);95<=d&&122>=d||65<=
d&&90>=d||48<=d&&57>=d||95===d;)d=c.charCodeAt(++b);h+=b-a;return{type:"Identifier",name:c.slice(a,b)}}function u(b,a){p()||l(x("Expected white space"));var c=j.charAt(h),m=k(y,c),e=[];m===A?">"!==c?e=d():l(x('Expected ">"')):(c=p(),">"!==j.charAt(h)&&(c||l(x('Expected ">"')),e=d()));g();++h;return{type:"Entity",id:b,value:m,index:a,K:e,f:95===b.name.charCodeAt(0)}}function v(){var a=j.charCodeAt(h);if(60===a){++h;var c=n(),a=j.charCodeAt(h);if(40===a){"_"===c.name.charAt(0)&&l(x('Macro ID cannot start with "_"'));
++h;a=O(f,")");p();"{"!==j.charAt(h)&&l(x('Expected "{"'));++h;g();var d=b();g();"}"!==j.charAt(h)&&l(x('Expected "}"'));++h;g();62!==j.charCodeAt(h)&&l(x('Expected ">"'));++h;return{type:"Macro",id:c,u:a,h:d}}return 91===a?(++h,u(c,O(z,"]"))):u(c,[])}if(47===j.charCodeAt(h)&&42===j.charCodeAt(h+1))return c=h+=2,a=j.indexOf("*/",c),-1===a&&l(x("Comment without closing tag")),h=a+2,{type:"Comment",content:j.slice(c,a)};if("import"===j.slice(h,h+6))return h+=6,"("!==j.charAt(h)&&l(x('Expected "("')),
++h,g(),c=e(j.charAt(h)),g(),")"!==j.charAt(h)&&l(x('Expected ")"')),++h,{type:"ImportStatement",uri:c};l(x("Invalid entry"))}function B(){var b=[];for(g();h<G;){try{b.push(v())}catch(a){a instanceof M?(H.l("error",a),b.push(pa())):l(a)}h<G&&g()}return{type:"LOL",body:b}}function q(){var b=[];for(g();h<G;)b.push(v()),h<G&&g();return{type:"LOL",body:b}}function z(){return b()}function r(b,a,c,d){for(var m=d(),e,s;;){e="";g();s=j.charAt(h);if(-1===b[0].indexOf(s))break;e+=s;++h;if(1<b.length)if(s=j.charAt(h),
b[1]==s)++h,e+=s;else if(b[2]){--h;break}g();m={type:a,w:{type:c,z:e},left:m,right:d()}}return m}function a(b,c,d,e){var m=j.charCodeAt(h);if(-1===b.indexOf(m))return e();++h;g();return{type:c,w:{type:d,z:String.fromCharCode(m)},R:a(b,c,d,e)}}function b(){var a=r([["|"],"|",y],"LogicalExpression","LogicalOperator",s);g();if(63!==j.charCodeAt(h))return a;++h;g();var c=b();g();58!==j.charCodeAt(h)&&l(x('Expected ":"'));++h;g();return{type:"ConditionalExpression",test:a,S:c,Q:b()}}function s(){return r([["&"],
"&",y],"LogicalExpression","Logicalperator",m)}function m(){return r([["="],"=",y],"BinaryExpression","BinaryOperator",ia)}function ia(){return r([["<",">"],"=",C],"BinaryExpression","BinaryOperator",N)}function N(){return r([["+","-"]],"BinaryExpression","BinaryOperator",na)}function na(){return r([["%"]],"BinaryExpression","BinaryOperator",oa)}function oa(){return r([["*"]],"BinaryExpression","BinaryOperator",la)}function la(){return r([["/"]],"BinaryExpression","BinaryOperator",ma)}function ma(){return a([43,
45,33],"UnaryExpression","UnaryOperator",ja)}function Y(a,c){"ParenthesisExpression"!==a.type&&("CallExpression"!==a.type&&"Identifier"!==a.type&&"ThisExpression"!==a.type)&&l(x("AttributeExpression must have Identifier, This, Call or Parenthesis as left node"));var d;if(c)return g(),d=b(),g(),"]"!==j.charAt(h)&&l(x('Expected "]"')),++h,{type:"AttributeExpression",h:a,F:d,s:y};d=n();return{type:"AttributeExpression",h:a,F:d,s:C}}function ja(){var a;if(40===j.charCodeAt(h)){++h;g();var c={type:"ParenthesisExpression",
h:b()};g();41!==j.charCodeAt(h)&&l(x('Expected ")"'));++h;a=c}else a=ka();for(;;)if(c=j.charCodeAt(h),46===c||91===c){++h;var d=w;91===c?(g(),d=b(),g(),"]"!==j.charAt(h)&&l(x('Expected "]"')),++h,a={type:"PropertyExpression",h:a,G:d,s:y}):(d=n(),a={type:"PropertyExpression",h:a,G:d,s:C})}else if(58===c&&58===j.charCodeAt(h+1))h+=2,91===j.charCodeAt(h)?(++h,a=Y(a,y)):a=Y(a,C);else if(40===c)++h,c=a,g(),a={type:"CallExpression",callee:c,arguments:O(z,")")};else break;return a}function ka(){for(var b=
h,a=j.charCodeAt(b);47<a&&58>a;)a=j.charCodeAt(++b);if(b>h)return a=h,h=b,{type:"Number",value:parseInt(j.slice(a,b),10)};switch(a){case 39:case 34:case 123:case 91:return k();case 36:return f();case 64:return++h,{type:"GlobalsExpression",id:n()};case 126:return++h,{type:"ThisExpression"};default:return n()}}function O(b,a){var c;g();if(j.charAt(h)===a)return++h,[];for(var d=[];;)if(d.push(b()),g(),c=j.charAt(h),","===c)++h,g();else if(c===a){++h;break}else l(x('Expected "," or "'+a+'"'));return d}
function x(b){var a;a===w&&(a=h);var c=j.lastIndexOf("<",a-1),d=j.lastIndexOf(">",a-1),c=j.slice(d>c?d+1:c,a+10);return new M(b+" at pos "+a+': "'+c+'"',a,c)}function pa(){var a=j.indexOf("<",h),b;if(-1===a)return b={type:"JunkEntry",content:j.slice(h)},h=G,b;b={type:"JunkEntry",content:j.slice(h,a)};h=a;return b}this.parse=function(a){j=a;h=0;G=j.length;return W()};this.W=function(a){j=a;h=0;G=j.length;try{var d;var e,m;a=h;for(var s=C,f=j.indexOf("\\");-1!==f;){e=j.charAt(f+1);if('"'==e||"'"==e||
"\\"==e)j=j.substr(0,f)+j.substr(f+1);f=j.indexOf("\\",f+1)}for(f=j.indexOf("{{");-1!==f;)92===j.charCodeAt(f-1)?(j=j.substr(0,f-1)+j.substr(f),f=j.indexOf("{{",f+2)):(s||(m=[],s=y),a<f&&m.push({type:"String",content:j.slice(a,f)}),h=f+2,g(),m.push(b()),g(),(125!==j.charCodeAt(h)||125!==j.charCodeAt(h+1))&&l(x('Expected "}}"')),a=f=h+2,f=j.indexOf("{{",f));s?(a<G&&m.push({type:"String",content:j.slice(a)}),d={type:"ComplexString",content:m}):d={type:"String",content:j};return d}catch(k){c&&k instanceof
M&&H.l("error",k),l(k)}};this.addEventListener=function(a,b){H||l(Error("Emitter not available"));return H.addEventListener(a,b)};this.removeEventListener=function(a,b){H||l(Error("Emitter not available"));return H.removeEventListener(a,b)};this.P=M;var j,h,G,H,W;c?(H=new c,W=B):W=q}function M(c,d,e){this.name="ParserError";this.message=c;this.ua=d;this.ka=e}M.prototype=Object.create(Error.prototype);"undefined"!==typeof exports?exports.C=L:this.t?this.t.C=L:this.ca=L;var da=L20n;
function P(){this.p={}}P.prototype.l=function(){var c=Array.prototype.slice.call(arguments),d=c.shift();(d=this.p[d])&&d.length&&d.forEach(function(d){d.apply(this,c)},this)};P.prototype.addEventListener=function(c,d){this.p[c]||(this.p[c]=[]);this.p[c].push(d);return this};P.prototype.removeEventListener=function(c,d){var e=this.p[c].indexOf(d);if(-1===e)return this;listeners.splice(e,1);return this};da.A=P;
function Q(c,d){function e(a,b,c){a=new a(b,c,w);v&&v.l("error",a);return a}function k(a){this.id=a.id.name;this.f=a.f||C;this.index=[];this.attributes={};var b;for(b=0;b<a.index.length;b++)this.index.push(f(a.index[b],this));for(b=0;b<a.K.length;b++){var c=a.K[b];this.attributes[c.key.name]=new p(c,this)}this.value=f(a.value,this,this.index)}function p(a,b){this.key=a.key.name;this.f=a.f||C;this.value=f(a.value,b,b.index);this.M=b}function g(a){this.id=a.id.name;this.f=a.f||C;this.h=f(a.h,this);
this.u=a.u}function f(a,b,c){if(!a)return A;r[a.type]||l(e("CompilationError","Unknown expression type"+a.type));c&&(c=c.slice());return r[a.type](a,b,c)}function n(a,b,c){if(!a||"string"===typeof a||"boolean"===typeof a||"number"===typeof a)return a;if(a.q)return a.q(c);a=a(b,c);b=a[0];a=a[1];return n(a,b,c)}function u(a,b){if("=="==a)return function(a,b){return a==b};if("!="==a)return function(a,b){return a!=b};if("<"==a)return function(a,b){return a<b};if("<="==a)return function(a,b){return a<=
b};if(">"==a)return function(a,b){return a>b};if(">="==a)return function(a,b){return a>=b};if("+"==a)return function(a,b){return a+b};if("-"==a)return function(a,b){return a-b};if("*"==a)return function(a,b){return a*b};if("/"==a)return function(a,c){0==c&&l(new R("Division by zero not allowed.",b));return a/c};if("%"==a)return function(a,b){return a%b};l(e(S,"Unknown token: "+a,b))}this.compile=function(a){q={};for(var b={$:k,da:g},c=0,d;d=a.body[c];c++){var e=b[d.type];if(e)try{q[d.id.name]=new e(d)}catch(f){T(f)}}return q};
this.X=function(a){z=a};this.addEventListener=function(a,b){v||l(Error("Emitter not available"));return v.addEventListener(a,b)};this.removeEventListener=function(a,b){v||l(Error("Emitter not available"));return v.removeEventListener(a,b)};this.reset=function(){q={};z={};return this};this.P=U;this.Y=S;this.fa=R;this.ga=V;this.aa=X;var v=c?new c:A,B=d?new d:A,q={},z;k.prototype.D=function(a,b){return this.value({n:this},a,b)};k.prototype.q=function(a){return n(this.value,{n:this},a)};k.prototype.toString=
function(a){try{return this.q(a)}catch(b){T(b),b instanceof V&&v&&v.l("error",b),l(b)}};p.prototype.D=function(a,b){return this.value({n:this.M},a,b)};p.prototype.q=function(a){return n(this.value,{n:this.M},a)};p.prototype.toString=function(a){return this.q(a)};g.prototype.J=function(a,b){for(var c={n:this},d=0;d<this.u.length;d++)c[this.u[d].id.name]=b[d];return this.h(c,a)};var r={Identifier:function(a,b){var c=a.name;return function(a){q.hasOwnProperty(c)||l(new R("Reference to an unknown entry: "+
c,b));a.n=q[c];return[a,q[c]]}},ThisExpression:function(){return function(a){return[a,a.n]}},VariableExpression:function(a,b){var c=a.id.name;return function(a,d){if(a.hasOwnProperty(c))return a[c];(!d||!d.hasOwnProperty(c))&&l(new R("Reference to an unknown variable: "+c,b));return[a,d[c]]}},GlobalsExpression:function(a,b){var c=a.id.name;return function(a){z||l(new R("Globals missing (tried @"+c+").",b));z.hasOwnProperty(c)||l(new R("Reference to an unknown global: "+c,b));return[a,z[c]]}},Number:function(a){return function(b){return[b,
a.value]}},String:function(a,b){var c,d;return function(e,g){if(!d){try{c=B.W(a.content)}catch(k){l(new V("Malformed string. "+k.message,b,a.content))}if("String"==c.type)return[e,c.content];d=f(c,b)}try{return[e,n(d,e,g)]}catch(p){T(p),l(new V(p.message,b,a.content))}}},Hash:function(a,b,c){for(var d=[],g=A,k=c.length?c.shift():A,p=0;p<a.content.length;p++){var q=a.content[p];d[q.key.name]=f(q.value,b,c);q.la&&(g=q.key.name)}return function(a,c,f){f=[f,k,g];for(var p=[],s=0;s<f.length;s++){try{var q=
f[s]=n(f[s],a,c)}catch(r){T(r),l(e(X,r.message,b))}q&&p.push(q);if(d.hasOwnProperty(q))return[a,d[q]]}l(e(X,p.length?"Hash key lookup failed (tried "+p.join(", ")+").":"Hash key lookup failed.",b))}},HashItem:f,ComplexString:function(a,b){for(var c=[],d=0;d<a.content.length;d++)c.push(f(a.content[d],b));var e=C;return function(a,d){e&&l(new R("Cyclic reference detected",b));e=y;var f=[];try{for(var g=0;g<c.length;g++)f.push(n(c[g],a,d))}finally{e=C}return[a,f.join("")]}},UnaryExpression:function(a,
b){var c;var d=a.w.z;"-"==d?c=function(a){return-a}:"+"==d?c=function(a){return+a}:"!"==d?c=function(a){return!a}:l(e(S,"Unknown token: "+d,b));var g=f(a.R,b);return function(a,b){return[a,c(n(g,a,b))]}},BinaryExpression:function(a,b){var c=f(a.left,b),d=u(a.w.z,b),e=f(a.right,b);return function(a,b){return[a,d(n(c,a,b),n(e,a,b))]}},LogicalExpression:function(a,b){var c=f(a.left,b),d;var g=a.w.z;"&&"==g?d=function(a,b){return a&&b}:"||"==g?d=function(a,b){return a||b}:l(e(S,"Unknown token: "+g,b));
var k=f(a.right,b);return function(a,b){return[a,d(n(c,a,b),n(k,a,b))]}},ConditionalExpression:function(a,b){var c=f(a.test,b),d=f(a.S,b),e=f(a.Q,b);return function(a,b){return n(c,a,b)?d(a,b):e(a,b)}},CallExpression:function(a,b){for(var c=f(a.callee,b),d=[],e=0;e<a.arguments.length;e++)d.push(f(a.arguments[e],b));return function(a,e){for(var f=[],g=0;g<d.length;g++)f.push(d[g](a,e));g=c(a,e);g=g[1];g.J||l(new R("Expected a macro, got a non-callable.",b));return g.J(e,f)}},PropertyExpression:function(a,
b){var c=f(a.h,b),d=a.s?f(a.G,b):a.G.name;return function(a,e){var g=n(d,a,e),f=c(a,e);a=f[0];f=f[1];return f.D?f.D(e,g):"function"!==typeof f?(f.hasOwnProperty(g)||l(new R(g+" is not defined in the context data",b)),[A,f[g]]):f(a,e,g)}},AttributeExpression:function(a,b){var c=f(a.h,b),d=a.s?f(a.F,b):a.F.name;return function(a,b){var e=n(d,a,b),f=c(a,b);a=f[0];f=f[1];return[a,f.attributes[e]]}},ParenthesisExpression:function(a,b){return f(a.h,b)}}}
function U(c,d){this.name="CompilerError";this.message=c;this.na=d.id}function S(c,d){U.call(this,c,d);this.name="CompilationError"}function R(c,d){U.call(this,c,d);this.name="RuntimeError"}function V(c,d,e){R.call(this,c,d);this.name="ValueError";this.source=e}function X(c,d){R.call(this,c,d);this.name="IndexError"}function T(c){c instanceof U||l(c)}U.prototype=Object.create(Error.prototype);S.prototype=Object.create(U.prototype);R.prototype=Object.create(U.prototype);V.prototype=Object.create(R.prototype);
X.prototype=Object.create(R.prototype);"undefined"!==typeof exports?exports.H=Q:this.t?this.t.H=Q:this.ba=Q;var ea={defaultLocale:"en-US",systemLocales:["en-US"]};
L20n.I={O:function(c){for(var d=[navigator.language||navigator.wa],e={localeMatcher:"lookup"},k=0,p=d.length,g=w;k<p&&g===w;){var f=d[k],n=f;a:{for(g=n;;){if(-1!==c.indexOf(g))break a;var u=g.lastIndexOf("-");if(-1===u)break;2<=u&&"-"==g[u-2]&&(u-=2);g=g.substr(0,u)}g=w}k+=1}d={};g!==w?(d.locale=g,f!==n&&l("NotImplemented")):d.locale=ea.ma;f=d.locale;d.hasOwnProperty("extension")&&l("NotImplemented");n="-u";for(d=0;0>d;)k=w(f)[f],p=k[0],g="",extensionSubtags!==w&&l("NotImplemented"),e.hasOwnProperty("key")&&
(u=e.key,-1!==k.indexOf(u)&&u!==p&&(g=""),n+=g,d+=1);2<n.length&&(f=f.substr(0,extensionIndex)+n+f.substr(extensionIndex+1));e=f;f=c.indexOf(e);if(-1===f)return c;c.splice(f,1);c.unshift(e);return c}};
function fa(){var c;if(0==Z.e.d.length&&(c=$.querySelector('meta[name="content-languages"]')))c=c.content.split(",").map(String.trim),Z.e.d=L20n.I.O(c);if(0==Z.e.c.length){c=$.querySelectorAll('meta[name="pathspec"]');for(var d=0;d<c.length;d++)Z.e.c.push(c[d].content)}if(c=$.querySelector('script[type="application/l10n-data+json"]'))Z.data=JSON.parse(c.textContent);for(var d=$.querySelectorAll('script[type="application/l10n"]'),e=0;e<d.length;e++)c=d[e],c.hasAttribute("pathspec")?Z.r(c.getAttribute("pathspec")):
c.hasAttribute("src")?Z.r(c.getAttribute("src")):Z.v(A,c.textContent);Z.addEventListener("ready",function(){var c=document.createEvent("Event");c.initEvent("LocalizationReady",C,C);document.dispatchEvent(c);document.body?ga():document.addEventListener("readystatechange",function(){"interactive"===document.readyState&&ga()})});Z.addEventListener("error",function(c){c.code&L20n.ea&&(c=document.createEvent("Event"),c.initEvent("LocalizationFailed",C,C),document.dispatchEvent(c))});Z.freeze()}
function ga(){for(var c=document.querySelectorAll("[data-l10n-id]"),d=0;d<c.length;d++)a:{var e=c[d],k=Z,p=e.getAttribute("data-l10n-id"),g=w;e.hasAttribute("data-l10n-data")&&(g=JSON.parse(e.getAttribute("data-l10n-data")));try{var f=k.T(p,g)}catch(n){console.warn("Failed to localize node: "+p);break a}p=A;e.hasAttribute("data-l10n-attrs")&&(p=e.getAttribute("data-l10n-attrs").split(" "));if(f.attributes)for(k in k=w,f.attributes)(!p||-1!==p.indexOf(k))&&e.setAttribute(k,f.attributes[k]);if(e.hasAttribute("data-l10n-overlay")){p=
e.U;p||(p=e.cloneNode(y),e.U=p);e.innerHTML=f.value;for(var g=e.getElementsByTagName("*"),u=w,k=0,v=w;v=g[k];k++)if(u=ha(v,e),u=document.evaluate(u,p,A,XPathResult.FIRST_ORDERED_NODE_TYPE,A).singleNodeValue)for(var B=0,q;q=u.attributes[B];B++)v.hasAttribute(q.name)||v.setAttribute(q.nodeName,q.value)}else e.textContent=f.value}c=document.createEvent("Event");c.initEvent("DocumentLocalized",C,C);document.dispatchEvent(c)}
function ha(c,d){if(c===d)return".";var e=c.getAttribute("id");if(e)return'*[@id="'+e+'"]';if(e=c.getAttribute("l10n-path"))return e;for(var e=0,k=c.parentNode.childNodes,p=0,g;g=k[p];p++){if(g===c)return ha(c.parentNode,d)+"/"+c.tagName+"["+(e+1)+"]";1===g.nodeType&&g.tagName===c.tagName&&e++}l("Can't find the path to element "+c)}var Z=L20n.getContext();HTMLDocument.prototype.__defineGetter__("l10n",function(){return Z});var $;$=document.head;var qa=$.querySelector('link[rel="l10n-manifest"]');
if(qa){var ra=qa.getAttribute("href"),sa=when.defer();L20n.B.N(ra).b(function(c){c=JSON.parse(c);var d=L20n.I.O(c.d);Z.e.d=d;Z.e.c=c.c;sa.a()});sa.j.b(fa)}else fa();
