/*
 MIT License (c) copyright B Cavalier & J Hann */
'use strict';function m(c){throw c;}var z=void 0,A=!0,B=null,D=!1;
("function"==typeof define&&define.da?define:function(c){"object"===typeof exports?module.ka=c():this.va=c()})(function(){function c(b,r,a,q){return d(b).b(r,a,q)}function d(b){var r,a;b instanceof f?r=b:g(b)?(a=t(),b.b(function(b){a.a(b)},function(b){a.h(b)},function(b){a.l(b)}),r=a.m):r=new f(function(a){try{return d(a?a(b):b)}catch(r){return p(r)}});return r}function f(b){this.b=b}function p(b){return new f(function(a,e){try{return e?d(e(b)):p(b)}catch(q){return p(q)}})}function t(){function b(b,
a,r){return l(b,a,r)}function r(b){return j(b)}function e(b){return j(p(b))}function q(b){return n(b)}var c,F,g,l,n,j;c={b:b,a:r,h:e,l:q,m:new f(b),ta:{a:r,h:e,l:q}};F=[];g=[];l=function(b,a,r){var e,q;e=t();q="function"===typeof r?function(b){try{e.l(r(b))}catch(a){e.l(a)}}:function(b){e.l(b)};F.push(function(r){r.b(b,a).b(e.a,e.h,q)});g.push(q);return e.m};n=function(b){u(g,b);return b};j=function(b){b=d(b);l=b.b;j=d;n=C;u(F,b);g=F=a;return b};return c}function g(b){return b&&"function"===typeof b.b}
function j(b,a,e,q,d){v(2,arguments);return c(b,function(b){function g(b){u(b)}function l(b){p(b)}var f,j,n,w,y,p,u,k,h,v;h=b.length>>>0;f=Math.max(0,Math.min(a,h));n=[];j=h-f+1;w=[];y=t();if(f){k=y.l;u=function(b){w.push(b);--j||(p=u=C,y.h(w))};p=function(b){n.push(b);--f||(p=u=C,y.a(n))};for(v=0;v<h;++v)v in b&&c(b[v],l,g,k)}else y.a(n);return y.b(e,q,d)})}function l(b,a){return c(b,function(b){var q,d,g,f,l,n;g=d=b.length>>>0;q=[];n=t();if(g){f=function(b,e){c(b,a).b(function(b){q[e]=b;--g||n.a(q)},
n.h)};for(l=0;l<d;l++)l in b?f(b[l],l):--g}else n.a(q);return n.m})}function u(b,a){for(var e,q=0;e=b[q++];)e(a)}function v(b,a){for(var e,q=a.length;q>b;)e=a[--q],e!=B&&"function"!=typeof e&&m(Error("arg "+q+" must be a function"))}function C(){}function w(b){return b}var y,n,a;c.defer=t;c.a=d;c.h=function(b){return c(b,p)};c.join=function(){return l(arguments,w)};c.all=function(b,a,e,q){v(1,arguments);return l(b,w).b(a,e,q)};c.map=l;c.reduce=function(b,a){var e=n.call(arguments,1);return c(b,function(b){var d;
d=b.length;e[0]=function(b,e,q){return c(b,function(b){return c(e,function(e){return a(b,e,q,d)})})};return y.apply(b,e)})};c.ea=function(b,a,e,q){return j(b,1,function(b){return a?a(b[0]):b[0]},e,q)};c.some=j;c.fa=function(b,a,e){var q=2<arguments.length;return c(b,function(b){b=q?e:b;a.a(b);return b},function(b){a.h(b);return p(b)},a.l)};c.pa=g;f.prototype={};n=[].slice;y=[].reduce||function(b){var a,e,q,c,d;d=0;a=Object(this);c=a.length>>>0;e=arguments;if(1>=e.length)for(;;){if(d in a){q=a[d++];
break}++d>=c&&m(new TypeError)}else q=e[1];for(;d<c;++d)d in a&&(q=b(q,a[d],d,a));return q};return c});function E(c,d){this.text=d;this.e=B;this.url=c}
function G(c,d,f){function p(d){var c=l.source.url.split("/").slice(0,-1).join("/");return"/"==d[0]?d:c?("/"==c[c.length-1]&&(c=c.slice(0,c.length-1)),c+"/"+d):"./"+d}function t(c,g){var f=when.defer(),n=J(c,d.j.g[0],d.j.d[g]);l.source&&(n=p(n));K.H.Q(n).b(function(a){f.a(new E(n,a))},function(){if(d.j.d.length>=g+1)t(c,g+1).b(function(a){return f.a(a)},function(){return f.a()});else return f.a()});return f.m}function g(c,f){var j=J(c,d.j.g[0],d.j.d[f]);l.source&&(j=p(j));var n=B;return d.j.d.length>=
f+1||0===d.j.d.length&&0===f?(n=K.H.R(j))?new E(j,n):g(c,f+1):D}function j(c,j,p){if(7<p)return D;var n=new G(c,d,f);l.i.push(n);if(j){var a=when.defer();u.push(a);t(c,0).b(function(b){b&&(n.source=b,n.parse(A,p))}).b(function(){a.a(n)})}else n.source=g(c,0),n.parse(D,p)}var l=this;this.id=c;this.i=[];this.source=B;this.o=D;this.e={type:"LOL",body:[]};this.K=function(){var c=when.defer();when.all(u).b(function(){var d=[];l.i.forEach(function(c){d.push(c.K())});when.all(d).b(function(){for(var d=0,
g;g=l.i[d];d++){var a=v[d];g.source&&(l.source===B?l.e.body=l.e.body.concat(g.source.e.body):Array.prototype.splice.apply(l.e.body,[a,1].concat(g.source.e.body)))}l.o=A;return c.a()})});return c.m};this.D=function(c,g){var l=new G(c,d,f),j=new E(c,g);l.source=j;j.e=f.parse(j.text);this.i.push(l);v.push(0)};this.B=j;this.parse=function(c,d){this.e=this.source.e=f.parse(this.source.text);this.source.e.body.filter(function(c,d){return"ImportStatement"==c.type?(v.push(d),A):D}).forEach(function(g){j(g.uri.content,
c,d+1)})};var u=[],v=[]}
function aa(c){function d(b,a){C.o||m("Error: context not ready");if(!w.hasOwnProperty(b)||w[b].c===A)return j("Missing entity",b),f(b,a);var e=w[b],c=p(a);try{return e.toString(c)}catch(d){return j("Entity could not be resolved",b),f(b,a,d.source)}}function f(b,r,e){var d;if(2>a.g.length)d=B;else{if(n===B){n=new aa(self);n.j.g=a.g.slice(1);n.addEventListener("error",g);a.d.length&&(n.j.d=a.d);for(d in C.i)C.i[d].id===B?n.D(B,C.i[d].source.text):n.B(C.i[d].id,D);n.freeze()}d=n}var f=B;d?f=d.get(b,
r):j("No more locale fallbacks",b);return c||f!==B?f:e?e:b}function p(b){if(!b)return y;var a={},e;for(e in y)y.hasOwnProperty(e)&&(a[e]=y[e]);if(b)for(e in b)b.hasOwnProperty(e)&&(a[e]=b[e]);return a}function t(b,a){var e={},c;for(c in b)e[b[c]]=d(b[c],a);return e}function g(b){l.k("error",b)}function j(b,r){l.k("error",new L(b,r,a.g[0]))}this.V=L;this.data={};this.o=this.isFrozen=B;this.D=function(b,a){C.D(b,a);return this};this.B=function(b,a){a===z&&(a=A);C.B(b,a,0);return this};this.freeze=function(){C.K().b(function(){w=
v.compile(C.e);l.k("ready")});return this};this.get=d;this.ma=function(b,a){C.o||m("Error: context not ready");(!w.hasOwnProperty(b)||w[b].c===A)&&m("Missing entity: "+b);var e=w[b],c=p(a),d={},g;for(g in e.attributes){var f=e.attributes[g];f.c||(d[g]=f.toString(c))}return{value:e.toString(c),attributes:d}};this.getAttribute=function(b,a,e){C.o||m("Error: context not ready");(!w.hasOwnProperty(b)||w[b].c===A)&&m("Missing entity: "+b);b=w[b];(!b.attributes.hasOwnProperty(a)||b.attributes[a].c===A)&&
m("No such attribute: "+a);return b.attributes[a].toString(p(e))};this.na=function(b,a){var e=when.defer();if(C.o){var c=t(b,a);e.a(c)}else setTimeout(function(){e.h()},500),self.addEventListener("ready",function(){var c=t(b,a);e.a(c)});return e.m};this.la=B;this.addEventListener=function(b,a){l.addEventListener(b,a)};this.removeEventListener=function(b,a){l.removeEventListener(b,a)};var l=new K.w,u=new K.z(K.w),v=new K.G(K.w,K.z),C=new G(B,this,u),w={},y={},n=B,a={locales:[],schemes:[],timeout:500};
u.addEventListener("error",g);v.addEventListener("error",g);v.T({get oa(){return(new Date).getHours()},get qa(){return/^MacIntel/.test(navigator.platform)?"mac":/^Linux/.test(navigator.platform)?"linux":/^Win/.test(navigatgor.platform)?"win":"unknown"},screen:{get width(){return document.body.clientWidth},get height(){return document.body.clientHeight}}});this.__defineSetter__("data",function(b){y=b});this.__defineGetter__("data",function(){return y});Object.defineProperty(this,"settings",{value:Object.create(Object.prototype,
{g:{get:function(){return a.g},set:function(b){Array.isArray(b)||m("Locales must be a list");0==b.length&&m("Locales list must not be empty");0<a.g.length&&m("Can't overwrite locales");a.g=b;Object.freeze(a.g)},configurable:D,enumerable:A},d:{get:function(){return a.d},set:function(b){Array.isArray(b)||m("Schemes must be a list");0==b.length&&m("Scheme list must not be empty");0<a.d.length&&m("Can't overwrite schemes");a.d=b;Object.freeze(a.d)},configurable:D,enumerable:A},timeout:{get:function(){return a.timeout},
set:function(b){"number"!==typeof b&&m("Timeout must be a number");a.timeout=b},configurable:D,enumerable:A}}),writable:D,enumerable:D,configurable:D})}function ba(c,d){return c.replace(/(\{\{\s*(\w+)\s*\}\})/g,function(c,p,t){if(d.hasOwnProperty(t))return d[t];m("Cannot use the undefined variable: "+t)})}
function J(c,d,f){if(!/^l10n:/.test(c))return c;var p=c.match(/^l10n:(?:([^:]+):)?([^:]+)/);p===B&&m("Malformed resource scheme: "+c);p[2]&&"/"==p[2][0]&&"/"==p[2][1]?(c=p[0].substring(5),p=""):(c=p[2],p=p[1]);var t={app:p,resource:c};d&&(t.locale=d);if(!f)return p&&m("You need to define schemes to use with app uris"),ba(c,t);f=f.substr(5);return ba(f,t)}function L(c,d,f){this.name="ContextError";this.id=d;this.locale=f;this.message=c+", locale: "+f+", id: "+d}var K={getContext:function(){return new aa}};
L.prototype=Object.create(Error.prototype);this.s=K;L20n.H={Q:function(c){var d=when.defer(),f=new XMLHttpRequest;f.overrideMimeType("text/plain");f.addEventListener("load",function(){200==f.status?d.a(f.responseText):d.h()});f.addEventListener("abort",function(c){return when.h(c)});f.open("GET",c,A);f.send("");return d.m},R:function(c){var d=new XMLHttpRequest;d.overrideMimeType("text/plain");d.open("GET",c,D);d.send("");return 200==d.status?d.responseText:D}};
function M(c){function d(){for(var b=[],a,e;!(a=l(),e=[],"["===k.charAt(h)&&(++h,g(),e=N(y,"]")),g(),":"!==k.charAt(h)&&m(x('Expected ":"')),++h,g(),a={type:z,key:a,value:p(),index:e},a.c="_"===a.key.name.charAt(0),b.push(a),a=t(),e=k.charAt(h),">"===e);)a||m(x('Expected ">"'));return b}function f(b){for(var a=b.length,e=h+a,c=k.indexOf(b,e);-1!==c&&92===k.charCodeAt(c-1)&&92!==k.charCodeAt(c-2);)c=k.indexOf(b,c+a);-1===c&&m(x("Unclosed string literal"));b=k.slice(e,c);h=c+a;return{type:"String",
content:b}}function p(b,a){a===z&&(a=k.charAt(h));if("'"===a||'"'===a)return a===k.charAt(h+1)&&a===k.charAt(h+2)?f(a+a+a):f(a);if("{"===a){var e;++h;g();if("}"===k.charAt(h))++h,e={type:"Hash",content:[]};else{var c,d;for(e=[];;){c=D;"*"===k.charAt(h)&&(++h,c&&m(x("Default item redefinition forbidden")),c=A);d=l();g();":"!==k.charAt(h)&&m(x('Expected ":"'));++h;g();d={type:"HashItem",key:d,value:p()};d["default"]=c;e.push(d);g();if(c=","===k.charAt(h))++h,g();if("}"===k.charAt(h)){++h;break}c||m(x('Expected "}"'))}e=
{type:"Hash",content:e}}return e}b||m(x("Unknown value type"));return B}function t(){for(var b=h,a=k.charCodeAt(b);32===a||10===a||9===a||13===a;)a=k.charCodeAt(++h);return h!==b}function g(){for(var b=k.charCodeAt(h);32===b||10===b||9===b||13===b;)b=k.charCodeAt(++h)}function j(){++h;return{type:"VariableExpression",id:l()}}function l(){var b=h,a=b,e=k,c=e.charCodeAt(a);(97>c||122<c)&&((65>c||90<c)&&95!==c)&&m(x("Identifier has to start with [a-zA-Z]"));for(c=e.charCodeAt(++b);95<=c&&122>=c||65<=
c&&90>=c||48<=c&&57>=c||95===c;)c=e.charCodeAt(++b);h+=b-a;return{type:"Identifier",name:e.slice(a,b)}}function u(b,a){t()||m(x("Expected white space"));var c=k.charAt(h),e=p(A,c),r=[];e===B?">"!==c?r=d():m(x('Expected ">"')):(c=t(),">"!==k.charAt(h)&&(c||m(x('Expected ">"')),r=d()));g();++h;return{type:"Entity",id:b,value:e,index:a,J:r,c:95===b.name.charCodeAt(0)}}function v(){var a=k.charCodeAt(h);if(60===a){++h;var c=l(),a=k.charCodeAt(h);if(40===a){"_"===c.name.charAt(0)&&m(x('Macro ID cannot start with "_"'));
++h;a=N(j,")");t();"{"!==k.charAt(h)&&m(x('Expected "{"'));++h;g();var e=b();g();"}"!==k.charAt(h)&&m(x('Expected "}"'));++h;g();62!==k.charCodeAt(h)&&m(x('Expected ">"'));++h;return{type:"Macro",id:c,t:a,f:e}}return 91===a?(++h,u(c,N(y,"]"))):u(c,[])}if(47===k.charCodeAt(h)&&42===k.charCodeAt(h+1))return c=h+=2,a=k.indexOf("*/",c),-1===a&&m(x("Comment without closing tag")),h=a+2,{type:"Comment",content:k.slice(c,a)};if("import"===k.slice(h,h+6))return h+=6,"("!==k.charAt(h)&&m(x('Expected "("')),
++h,g(),c=f(k.charAt(h)),g(),")"!==k.charAt(h)&&m(x('Expected ")"')),++h,{type:"ImportStatement",uri:c};m(x("Invalid entry"))}function C(){var b=[];for(g();h<H;){try{b.push(v())}catch(a){a instanceof O?(I.k("error",a),b.push(ia())):m(a)}h<H&&g()}return{type:"LOL",body:b}}function w(){var b=[];for(g();h<H;)b.push(v()),h<H&&g();return{type:"LOL",body:b}}function y(){return b()}function n(b,a,c,e){for(var d=e(),r,q;;){r="";g();q=k.charAt(h);if(-1===b[0].indexOf(q))break;r+=q;++h;if(1<b.length)if(q=k.charAt(h),
b[1]==q)++h,r+=q;else if(b[2]){--h;break}g();d={type:a,u:{type:c,v:r},left:d,right:e()}}return d}function a(b,c,e,d){var r=k.charCodeAt(h);if(-1===b.indexOf(r))return d();++h;g();return{type:c,u:{type:e,v:String.fromCharCode(r)},O:a(b,c,e,d)}}function b(){var a=n([["|"],"|",A],"LogicalExpression","LogicalOperator",r);g();if(63!==k.charCodeAt(h))return a;++h;g();var c=b();g();58!==k.charCodeAt(h)&&m(x('Expected ":"'));++h;g();return{type:"ConditionalExpression",test:a,P:c,N:b()}}function r(){return n([["&"],
"&",A],"LogicalExpression","Logicalperator",e)}function e(){return n([["="],"=",A],"BinaryExpression","BinaryOperator",q)}function q(){return n([["<",">"],"=",D],"BinaryExpression","BinaryOperator",ca)}function ca(){return n([["+","-"]],"BinaryExpression","BinaryOperator",F)}function F(){return n([["%"]],"BinaryExpression","BinaryOperator",ha)}function ha(){return n([["*"]],"BinaryExpression","BinaryOperator",fa)}function fa(){return n([["/"]],"BinaryExpression","BinaryOperator",ga)}function ga(){return a([43,
45,33],"UnaryExpression","UnaryOperator",da)}function X(a,c){"ParenthesisExpression"!==a.type&&("CallExpression"!==a.type&&"Identifier"!==a.type&&"ThisExpression"!==a.type)&&m(x("AttributeExpression must have Identifier, This, Call or Parenthesis as left node"));var e;if(c)return g(),e=b(),g(),"]"!==k.charAt(h)&&m(x('Expected "]"')),++h,{type:"AttributeExpression",f:a,C:e,r:A};e=l();return{type:"AttributeExpression",f:a,C:e,r:D}}function da(){var a;if(40===k.charCodeAt(h)){++h;g();var c={type:"ParenthesisExpression",
f:b()};g();41!==k.charCodeAt(h)&&m(x('Expected ")"'));++h;a=c}else a=ea();for(;;)if(c=k.charCodeAt(h),46===c||91===c){++h;var e=z;91===c?(g(),e=b(),g(),"]"!==k.charAt(h)&&m(x('Expected "]"')),++h,a={type:"PropertyExpression",f:a,F:e,r:A}):(e=l(),a={type:"PropertyExpression",f:a,F:e,r:D})}else if(58===c&&58===k.charCodeAt(h+1))h+=2,91===k.charCodeAt(h)?(++h,a=X(a,A)):a=X(a,D);else if(40===c)++h,c=a,g(),a={type:"CallExpression",callee:c,arguments:N(y,")")};else break;return a}function ea(){for(var b=
h,a=k.charCodeAt(b);47<a&&58>a;)a=k.charCodeAt(++b);if(b>h)return a=h,h=b,{type:"Number",value:parseInt(k.slice(a,b),10)};switch(a){case 39:case 34:case 123:case 91:return p();case 36:return j();case 64:return++h,{type:"GlobalsExpression",id:l()};case 126:return++h,{type:"ThisExpression"};default:return l()}}function N(b,a){var c;g();if(k.charAt(h)===a)return++h,[];for(var e=[];;)if(e.push(b()),g(),c=k.charAt(h),","===c)++h,g();else if(c===a){++h;break}else m(x('Expected "," or "'+a+'"'));return e}
function x(b){var a;a===z&&(a=h);var c=k.lastIndexOf("<",a-1),e=k.lastIndexOf(">",a-1),c=k.slice(e>c?e+1:c,a+10);return new O(b+" at pos "+a+': "'+c+'"',a,c)}function ia(){var a=k.indexOf("<",h),b;if(-1===a)return b={type:"JunkEntry",content:k.slice(h)},h=H,b;b={type:"JunkEntry",content:k.slice(h,a)};h=a;return b}this.parse=function(a){k=a;h=0;H=k.length;return V()};this.S=function(a){k=a;h=0;H=k.length;try{var e;var d,r;a=h;for(var q=D,f=k.indexOf("\\");-1!==f;){d=k.charAt(f+1);if('"'==d||"'"==d||
"\\"==d)k=k.substr(0,f)+k.substr(f+1);f=k.indexOf("\\",f+1)}for(f=k.indexOf("{{");-1!==f;)92===k.charCodeAt(f-1)?(k=k.substr(0,f-1)+k.substr(f),f=k.indexOf("{{",f+2)):(q||(r=[],q=A),a<f&&r.push({type:"String",content:k.slice(a,f)}),h=f+2,g(),r.push(b()),g(),(125!==k.charCodeAt(h)||125!==k.charCodeAt(h+1))&&m(x('Expected "}}"')),a=f=h+2,f=k.indexOf("{{",f));q?(a<H&&r.push({type:"String",content:k.slice(a)}),e={type:"ComplexString",content:r}):e={type:"String",content:k};return e}catch(l){c&&l instanceof
O&&I.k("error",l),m(l)}};this.addEventListener=function(a,b){I||m(Error("Emitter not available"));return I.addEventListener(a,b)};this.removeEventListener=function(a,b){I||m(Error("Emitter not available"));return I.removeEventListener(a,b)};this.M=O;var k,h,H,I,V;c?(I=new c,V=C):V=w}function O(c,d,f){this.name="ParserError";this.message=c;this.ra=d;this.ga=f}O.prototype=Object.create(Error.prototype);"undefined"!==typeof exports?exports.z=M:this.s?this.s.z=M:this.$=M;var ja=L20n;
function P(){this.p={}}P.prototype.k=function(){var c=Array.prototype.slice.call(arguments),d=c.shift();(d=this.p[d])&&d.length&&d.forEach(function(d){d.apply(this,c)},this)};P.prototype.addEventListener=function(c,d){this.p[c]||(this.p[c]=[]);this.p[c].push(d);return this};P.prototype.removeEventListener=function(c,d){var f=this.p[c].indexOf(d);if(-1===f)return this;listeners.splice(f,1);return this};ja.w=P;
function Q(c,d){function f(a,b,c){a=new a(b,c,z);v&&v.k("error",a);return a}function p(a){this.id=a.id.name;this.c=a.c||D;this.index=[];this.attributes={};var b;for(b=0;b<a.index.length;b++)this.index.push(j(a.index[b],this));for(b=0;b<a.J.length;b++){var c=a.J[b];this.attributes[c.key.name]=new t(c,this)}this.value=j(a.value,this,this.index)}function t(a,b){this.key=a.key.name;this.c=a.c||D;this.value=j(a.value,b,b.index);this.L=b}function g(a){this.id=a.id.name;this.c=a.c||D;this.f=j(a.f,this);
this.t=a.t}function j(a,b,c){if(!a)return B;n[a.type]||m(f("CompilationError","Unknown expression type"+a.type));c&&(c=c.slice());return n[a.type](a,b,c)}function l(a,b,c){if(!a||"string"===typeof a||"boolean"===typeof a||"number"===typeof a)return a;if(a.q)return a.q(c);a=a(b,c);b=a[0];a=a[1];return l(a,b,c)}function u(a,b){if("=="==a)return function(a,b){return a==b};if("!="==a)return function(a,b){return a!=b};if("<"==a)return function(a,b){return a<b};if("<="==a)return function(a,b){return a<=
b};if(">"==a)return function(a,b){return a>b};if(">="==a)return function(a,b){return a>=b};if("+"==a)return function(a,b){return a+b};if("-"==a)return function(a,b){return a-b};if("*"==a)return function(a,b){return a*b};if("/"==a)return function(a,c){0==c&&m(new R("Division by zero not allowed.",b));return a/c};if("%"==a)return function(a,b){return a%b};m(f(S,"Unknown token: "+a,b))}this.compile=function(a){w={};for(var b={W:p,aa:g},c=0,e;e=a.body[c];c++){var d=b[e.type];if(d)try{w[e.id.name]=new d(e)}catch(f){T(f)}}return w};
this.T=function(a){y=a};this.addEventListener=function(a,b){v||m(Error("Emitter not available"));return v.addEventListener(a,b)};this.removeEventListener=function(a,b){v||m(Error("Emitter not available"));return v.removeEventListener(a,b)};this.reset=function(){w={};y={};return this};this.M=U;this.U=S;this.ba=R;this.ca=W;this.X=Y;var v=c?new c:B,C=d?new d:B,w={},y;p.prototype.A=function(a,b){return this.value({n:this},a,b)};p.prototype.q=function(a){return l(this.value,{n:this},a)};p.prototype.toString=
function(a){try{return this.q(a)}catch(b){T(b),b instanceof W&&v&&v.k("error",b),m(b)}};t.prototype.A=function(a,b){return this.value({n:this.L},a,b)};t.prototype.q=function(a){return l(this.value,{n:this.L},a)};t.prototype.toString=function(a){return this.q(a)};g.prototype.I=function(a,b){for(var c={n:this},e=0;e<this.t.length;e++)c[this.t[e].id.name]=b[e];return this.f(c,a)};var n={Identifier:function(a,b){var c=a.name;return function(a){w.hasOwnProperty(c)||m(new R("Reference to an unknown entry: "+
c,b));a.n=w[c];return[a,w[c]]}},ThisExpression:function(){return function(a){return[a,a.n]}},VariableExpression:function(a,b){var c=a.id.name;return function(a,d){if(a.hasOwnProperty(c))return a[c];(!d||!d.hasOwnProperty(c))&&m(new R("Reference to an unknown variable: "+c,b));return[a,d[c]]}},GlobalsExpression:function(a,b){var c=a.id.name;return function(a){y||m(new R("Globals missing (tried @"+c+").",b));y.hasOwnProperty(c)||m(new R("Reference to an unknown global: "+c,b));return[a,y[c]]}},Number:function(a){return function(b){return[b,
a.value]}},String:function(a,b){var c,e;return function(d,f){if(!e){try{c=C.S(a.content)}catch(g){m(new W("Malformed string. "+g.message,b,a.content))}if("String"==c.type)return[d,c.content];e=j(c,b)}try{return[d,l(e,d,f)]}catch(n){T(n),m(new W(n.message,b,a.content))}}},Hash:function(a,b,c){for(var e=[],d=B,g=c.length?c.shift():B,n=0;n<a.content.length;n++){var p=a.content[n];e[p.key.name]=j(p.value,b,c);p.ha&&(d=p.key.name)}return function(a,c,j){j=[j,g,d];for(var r=[],n=0;n<j.length;n++){try{var p=
j[n]=l(j[n],a,c)}catch(F){T(F),m(f(Y,F.message,b))}p&&r.push(p);if(e.hasOwnProperty(p))return[a,e[p]]}m(f(Y,r.length?"Hash key lookup failed (tried "+r.join(", ")+").":"Hash key lookup failed.",b))}},HashItem:j,ComplexString:function(a,b){for(var c=[],e=0;e<a.content.length;e++)c.push(j(a.content[e],b));var d=D;return function(a,e){d&&m(new R("Cyclic reference detected",b));d=A;var f=[];try{for(var g=0;g<c.length;g++)f.push(l(c[g],a,e))}finally{d=D}return[a,f.join("")]}},UnaryExpression:function(a,
b){var c;var e=a.u.v;"-"==e?c=function(a){return-a}:"+"==e?c=function(a){return+a}:"!"==e?c=function(a){return!a}:m(f(S,"Unknown token: "+e,b));var d=j(a.O,b);return function(a,b){return[a,c(l(d,a,b))]}},BinaryExpression:function(a,b){var c=j(a.left,b),e=u(a.u.v,b),d=j(a.right,b);return function(a,b){return[a,e(l(c,a,b),l(d,a,b))]}},LogicalExpression:function(a,b){var c=j(a.left,b),d;var g=a.u.v;"&&"==g?d=function(a,b){return a&&b}:"||"==g?d=function(a,b){return a||b}:m(f(S,"Unknown token: "+g,b));
var n=j(a.right,b);return function(a,b){return[a,d(l(c,a,b),l(n,a,b))]}},ConditionalExpression:function(a,b){var c=j(a.test,b),d=j(a.P,b),f=j(a.N,b);return function(a,b){return l(c,a,b)?d(a,b):f(a,b)}},CallExpression:function(a,b){for(var c=j(a.callee,b),d=[],f=0;f<a.arguments.length;f++)d.push(j(a.arguments[f],b));return function(a,f){for(var g=[],j=0;j<d.length;j++)g.push(d[j](a,f));j=c(a,f);j=j[1];j.I||m(new R("Expected a macro, got a non-callable.",b));return j.I(f,g)}},PropertyExpression:function(a,
b){var c=j(a.f,b),d=a.r?j(a.F,b):a.F.name;return function(a,f){var g=l(d,a,f),j=c(a,f);a=j[0];j=j[1];return j.A?j.A(f,g):"function"!==typeof j?(j.hasOwnProperty(g)||m(new R(g+" is not defined in the context data",b)),[B,j[g]]):j(a,f,g)}},AttributeExpression:function(a,b){var c=j(a.f,b),d=a.r?j(a.C,b):a.C.name;return function(a,b){var f=l(d,a,b),g=c(a,b);a=g[0];g=g[1];return[a,g.attributes[f]]}},ParenthesisExpression:function(a,b){return j(a.f,b)}}}
function U(c,d){this.name="CompilerError";this.message=c;this.ja=d.id}function S(c,d){U.call(this,c,d);this.name="CompilationError"}function R(c,d){U.call(this,c,d);this.name="RuntimeError"}function W(c,d,f){R.call(this,c,d);this.name="ValueError";this.source=f}function Y(c,d){R.call(this,c,d);this.name="IndexError"}function T(c){c instanceof U||m(c)}U.prototype=Object.create(Error.prototype);S.prototype=Object.create(U.prototype);R.prototype=Object.create(U.prototype);W.prototype=Object.create(R.prototype);
Y.prototype=Object.create(R.prototype);"undefined"!==typeof exports?exports.G=Q:this.s?this.s.G=Q:this.Z=Q;var ka={defaultLocale:"en-US",systemLocales:["en-US"]};
L20n.Y={sa:function(c){for(var d=[navigator.language||navigator.ua],f={localeMatcher:"lookup"},p=0,t=d.length,g=z;p<t&&g===z;){var j=d[p],l=j;a:{for(g=l;;){if(-1!==c.indexOf(g))break a;var u=g.lastIndexOf("-");if(-1===u)break;2<=u&&"-"==g[u-2]&&(u-=2);g=g.substr(0,u)}g=z}p+=1}d={};g!==z?(d.locale=g,j!==l&&m("NotImplemented")):d.locale=ka.ia;j=d.locale;d.hasOwnProperty("extension")&&m("NotImplemented");l="-u";for(d=0;0>d;)p=z(j)[j],t=p[0],g="",extensionSubtags!==z&&m("NotImplemented"),f.hasOwnProperty("key")&&
(u=f.key,-1!==p.indexOf(u)&&u!==t&&(g=""),l+=g,d+=1);2<l.length&&(j=j.substr(0,extensionIndex)+l+j.substr(extensionIndex+1));f=j;j=c.indexOf(f);if(-1===j)return c;c.splice(j,1);c.unshift(f);return c}};
